// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Dax.Vpax.CLI.Commands.Browse.BrowseRelationshipCommandHandler.GetView(System.CommandLine.Invocation.InvocationContext,Dax.Metadata.Model)~Spectre.Console.Rendering.IRenderable")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "<Pending>", Scope = "member", Target = "~M:Dax.Vpax.CLI.Commands.Browse.BrowseRelationshipCommandHandler.GetView(System.CommandLine.Invocation.InvocationContext,Dax.Metadata.Model)~Spectre.Console.Rendering.IRenderable")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Dax.Vpax.CLI.Commands.Package.PackageShowCommandHandler.GetContent(System.IO.FileInfo)~Spectre.Console.Rendering.IRenderable")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "<Pending>", Scope = "member", Target = "~M:Dax.Vpax.CLI.Commands.Package.PackageShowCommandHandler.GetContent(System.IO.FileInfo)~Spectre.Console.Rendering.IRenderable")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Dax.Vpax.CLI.Commands.Package.PackageShowCommandHandler.GetProperties(System.IO.FileInfo)~Spectre.Console.Rendering.IRenderable")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "<Pending>", Scope = "member", Target = "~M:Dax.Vpax.CLI.Commands.Package.PackageShowCommandHandler.GetProperties(System.IO.FileInfo)~Spectre.Console.Rendering.IRenderable")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Dax.Vpax.CLI.Commands.Browse.BrowseColumnCommandHandler.GetView(System.CommandLine.Invocation.InvocationContext,Dax.Metadata.Model)~Spectre.Console.Rendering.IRenderable")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Dax.Vpax.CLI.Commands.Browse.BrowseModelCommandHandler.GetTableView(Dax.Metadata.Model)~Spectre.Console.Rendering.IRenderable")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Dax.Vpax.CLI.Commands.Browse.BrowseModelCommandHandler.GetChartView(Dax.Metadata.Model)~Spectre.Console.Rendering.IRenderable")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Dax.Vpax.CLI.Commands.Browse.BrowseTableCommandHandler.GetView(System.CommandLine.Invocation.InvocationContext,Dax.Metadata.Model)~Spectre.Console.Rendering.IRenderable")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "<Pending>", Scope = "member", Target = "~M:Dax.Vpax.CLI.Commands.Browse.BrowseTableCommandHandler.GetView(System.CommandLine.Invocation.InvocationContext,Dax.Metadata.Model)~Spectre.Console.Rendering.IRenderable")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "<Pending>", Scope = "member", Target = "~M:Dax.Vpax.CLI.Commands.Browse.BrowseModelCommandHandler.GetChartView(Dax.Metadata.Model)~Spectre.Console.Rendering.IRenderable")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Dax.Vpax.CLI.Commands.CommandHandler.GetCurrentVpax(System.CommandLine.Invocation.InvocationContext)~System.IO.FileInfo")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "<Pending>", Scope = "member", Target = "~M:Dax.Vpax.CLI.Commands.Browse.BrowseColumnCommandHandler.GetView(System.CommandLine.Invocation.InvocationContext,Dax.Metadata.Model)~Spectre.Console.Rendering.IRenderable")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "<Pending>", Scope = "member", Target = "~M:Dax.Vpax.CLI.Commands.Browse.BrowseModelCommandHandler.GetTableView(Dax.Metadata.Model)~Spectre.Console.Rendering.IRenderable")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:Dax.Vpax.CLI.Commands.Browse.BrowseModelCommandHandler.GetTableView(Dax.Metadata.Model)~Spectre.Console.Rendering.IRenderable")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:Dax.Vpax.CLI.Commands.Browse.BrowseColumnCommandHandler.GetView(System.CommandLine.Invocation.InvocationContext,Dax.Metadata.Model)~Spectre.Console.Rendering.IRenderable")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:Dax.Vpax.CLI.Commands.Browse.BrowseRelationshipCommandHandler.GetView(System.CommandLine.Invocation.InvocationContext,Dax.Metadata.Model)~Spectre.Console.Rendering.IRenderable")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:Dax.Vpax.CLI.Commands.Browse.BrowseTableCommandHandler.GetView(System.CommandLine.Invocation.InvocationContext,Dax.Metadata.Model)~Spectre.Console.Rendering.IRenderable")]
