// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Dax.Vpax.CLI.Commands.Browse.BrowseRelationshipCommandHandler.GetRelationshipView(System.CommandLine.Invocation.InvocationContext,Dax.Metadata.Model)~Spectre.Console.Rendering.IRenderable")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "<Pending>", Scope = "member", Target = "~M:Dax.Vpax.CLI.Commands.Browse.BrowseRelationshipCommandHandler.GetRelationshipView(System.CommandLine.Invocation.InvocationContext,Dax.Metadata.Model)~Spectre.Console.Rendering.IRenderable")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Dax.Vpax.CLI.Commands.Package.PackageShowCommandHandler.GetContent(System.IO.FileInfo)~Spectre.Console.Rendering.IRenderable")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "<Pending>", Scope = "member", Target = "~M:Dax.Vpax.CLI.Commands.Package.PackageShowCommandHandler.GetContent(System.IO.FileInfo)~Spectre.Console.Rendering.IRenderable")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Dax.Vpax.CLI.Commands.Package.PackageShowCommandHandler.GetProperties(System.IO.FileInfo)~Spectre.Console.Rendering.IRenderable")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "<Pending>", Scope = "member", Target = "~M:Dax.Vpax.CLI.Commands.Package.PackageShowCommandHandler.GetProperties(System.IO.FileInfo)~Spectre.Console.Rendering.IRenderable")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Dax.Vpax.CLI.Commands.Browse.BrowseColumnCommandHandler.GetColumns(System.CommandLine.Invocation.InvocationContext,Dax.Metadata.Model)~Spectre.Console.Rendering.IRenderable")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Dax.Vpax.CLI.Commands.Browse.BrowseModelCommandHandler.GetProperties(Dax.Metadata.Model)~Spectre.Console.Rendering.IRenderable")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Dax.Vpax.CLI.Commands.Browse.BrowseModelCommandHandler.GetSizeChart(Dax.Metadata.Model)~Spectre.Console.Rendering.IRenderable")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Dax.Vpax.CLI.Commands.Browse.BrowseTableCommandHandler.GetTables(System.CommandLine.Invocation.InvocationContext,Dax.Metadata.Model)~Spectre.Console.Rendering.IRenderable")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "<Pending>", Scope = "member", Target = "~M:Dax.Vpax.CLI.Commands.Browse.BrowseTableCommandHandler.GetTables(System.CommandLine.Invocation.InvocationContext,Dax.Metadata.Model)~Spectre.Console.Rendering.IRenderable")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "<Pending>", Scope = "member", Target = "~M:Dax.Vpax.CLI.Commands.Browse.BrowseModelCommandHandler.GetSizeChart(Dax.Metadata.Model)~Spectre.Console.Rendering.IRenderable")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Dax.Vpax.CLI.Commands.CommandHandler.GetCurrentPackage(System.CommandLine.Invocation.InvocationContext)~System.IO.FileInfo")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "<Pending>", Scope = "member", Target = "~M:Dax.Vpax.CLI.Commands.Browse.BrowseColumnCommandHandler.GetColumns(System.CommandLine.Invocation.InvocationContext,Dax.Metadata.Model)~Spectre.Console.Rendering.IRenderable")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "<Pending>", Scope = "member", Target = "~M:Dax.Vpax.CLI.Commands.Browse.BrowseModelCommandHandler.GetProperties(Dax.Metadata.Model)~Spectre.Console.Rendering.IRenderable")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:Dax.Vpax.CLI.Commands.Browse.BrowseModelCommandHandler.GetProperties(Dax.Metadata.Model)~Spectre.Console.Rendering.IRenderable")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:Dax.Vpax.CLI.Commands.Browse.BrowseColumnCommandHandler.GetColumns(System.CommandLine.Invocation.InvocationContext,Dax.Metadata.Model)~Spectre.Console.Rendering.IRenderable")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:Dax.Vpax.CLI.Commands.Browse.BrowseRelationshipCommandHandler.GetRelationshipView(System.CommandLine.Invocation.InvocationContext,Dax.Metadata.Model)~Spectre.Console.Rendering.IRenderable")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:Dax.Vpax.CLI.Commands.Browse.BrowseTableCommandHandler.GetTables(System.CommandLine.Invocation.InvocationContext,Dax.Metadata.Model)~Spectre.Console.Rendering.IRenderable")]
[assembly: SuppressMessage("Performance", "CA1849:Call async methods when in an async method", Justification = "<Pending>", Scope = "member", Target = "~M:Dax.Vpax.CLI.Commands.Package.PackageObfuscateCommandHandler.InvokeAsync(System.CommandLine.Invocation.InvocationContext)~System.Threading.Tasks.Task{System.Int32}")]
[assembly: SuppressMessage("Performance", "CA1849:Call async methods when in an async method", Justification = "<Pending>", Scope = "member", Target = "~M:Dax.Vpax.CLI.Commands.Package.PackageDeobfuscateCommandHandler.InvokeAsync(System.CommandLine.Invocation.InvocationContext)~System.Threading.Tasks.Task{System.Int32}")]
