{
  "name": "d3216176-89dc-4cdb-8d3d-797be166a61a",
  "compatibilityLevel": 1567,
  "createdTimestamp": "2021-03-27T19:03:55.803333+01:00",
  "lastUpdate": "2023-03-28T15:46:54.613333+02:00",
  "lastSchemaUpdate": "2023-03-28T15:46:53.743333+02:00",
  "lastProcessed": "2021-04-20T17:58:07.836667+02:00",
  "model": {
    "culture": "it-IT",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "discourageImplicitMeasures": true,
    "sourceQueryCulture": "it-IT",
    "modifiedTime": "2021-03-27T22:13:58.67",
    "structureModifiedTime": "2021-04-06T21:23:50.76",
    "tables": [
      {
        "name": "Genere",
        "lineageTag": "1000f96d-bf06-4aec-a4f8-210093296955",
        "modifiedTime": "2021-03-27T18:03:55.97",
        "structureModifiedTime": "2021-03-30T07:32:14.273333",
        "columns": [
          {
            "type": "rowNumber",
            "name": "RowNumber-2662979B-1795-4F74-8F37-6A1BA8059B61",
            "dataType": "int64",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "isNullable": false,
            "modifiedTime": "2021-03-27T18:03:55.973333",
            "structureModifiedTime": "2021-03-27T18:03:55.97",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T18:04:01.216667",
              "refreshedTime": "2021-04-20T15:58:07.47"
            }
          },
          {
            "name": "CodiceGenere",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CodiceGenere",
            "lineageTag": "bfb5e176-a0f8-4325-a5de-0be5f5a3223d",
            "summarizeBy": "none",
            "modifiedTime": "2021-03-27T18:03:55.973333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T18:04:01.22",
              "refreshedTime": "2021-04-20T15:58:07.47"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T18:03:55.973333"
              }
            ]
          },
          {
            "name": "Genere",
            "dataType": "string",
            "sourceColumn": "Genere",
            "lineageTag": "0f2c7512-68a6-4f9e-8a45-8d312db463ca",
            "summarizeBy": "none",
            "modifiedTime": "2021-03-27T18:03:55.973333",
            "structureModifiedTime": "2021-03-27T18:03:55.973333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T18:04:01.216667",
              "refreshedTime": "2021-04-20T15:58:07.47"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T18:03:55.973333"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Genere-814fd887-51ef-47ee-9daf-1cc4583af3fc",
            "mode": "import",
            "state": "ready",
            "modifiedTime": "2021-04-20T11:01:05.566667",
            "refreshedTime": "2021-04-20T15:58:07.453333",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WclPSUXJLzc3NzMvMSVWK1YlW8gWK+CYWJ2eABWIB\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [CodiceGenere = _t, Genere = _t]),\n    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"CodiceGenere\", type text}, {\"Genere\", type text}})\nin\n    #\"Changed Type\""
            }
          }
        ],
        "hierarchies": [
          {
            "name": "CodiceGenere Hierarchy",
            "lineageTag": "79b48d3b-f668-4ea4-8367-504564ec1bb6",
            "state": "ready",
            "modifiedTime": "2021-03-30T12:16:17.993333",
            "structureModifiedTime": "2021-03-30T07:32:14.273333",
            "refreshedTime": "2021-04-20T15:58:07.473333",
            "levels": [
              {
                "name": "CodiceGenere",
                "ordinal": 0,
                "column": "CodiceGenere",
                "lineageTag": "def8d25a-8aa7-46f5-94aa-918e16ef882c",
                "modifiedTime": "2021-03-30T07:32:14.273333"
              },
              {
                "name": "Genere",
                "ordinal": 1,
                "column": "Genere",
                "lineageTag": "1ee70e3d-50b4-47ce-8a0c-1c9934427df1",
                "modifiedTime": "2021-03-30T07:32:14.273333"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table",
            "modifiedTime": "2021-03-27T18:03:55.973333"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation",
            "modifiedTime": "2021-04-20T15:58:06.396667"
          }
        ]
      },
      {
        "name": "Età",
        "lineageTag": "d8793317-9fdc-4c66-98c8-0de0e9b15778",
        "modifiedTime": "2021-03-27T18:03:55.97",
        "structureModifiedTime": "2021-03-27T20:37:51.986667",
        "columns": [
          {
            "type": "rowNumber",
            "name": "RowNumber-2662979B-1795-4F74-8F37-6A1BA8059B61",
            "dataType": "int64",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "isNullable": false,
            "modifiedTime": "2021-03-27T18:03:55.973333",
            "structureModifiedTime": "2021-03-27T18:03:55.97",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T18:04:01.243333",
              "refreshedTime": "2021-04-20T15:58:07.65"
            }
          },
          {
            "name": "Età",
            "dataType": "string",
            "sourceColumn": "Età",
            "lineageTag": "1af00971-c4ac-4c96-b375-0bc9487020f0",
            "summarizeBy": "none",
            "modifiedTime": "2021-03-30T12:25:51.773333",
            "structureModifiedTime": "2021-03-27T18:03:55.973333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T18:04:01.243333",
              "refreshedTime": "2021-04-20T15:58:07.66"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T18:03:55.973333"
              }
            ]
          },
          {
            "name": "FasciaAnagrafica",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "FasciaAnagrafica",
            "lineageTag": "19a08ea2-4e82-45f2-ab45-bcd92d7cd2b2",
            "summarizeBy": "none",
            "modifiedTime": "2021-03-27T18:03:55.973333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T18:04:01.243333",
              "refreshedTime": "2021-04-20T15:58:07.646667"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T18:03:55.973333"
              }
            ]
          },
          {
            "name": "Min2020",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Min2020",
            "formatString": "0",
            "lineageTag": "e63adc50-d7c8-4b17-a0d0-227e06cb674e",
            "summarizeBy": "none",
            "modifiedTime": "2021-03-27T20:39:50.15",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T20:37:52.25",
              "refreshedTime": "2021-04-20T15:58:07.66"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2021-03-27T20:39:47.646667"
              }
            ]
          },
          {
            "name": "Max2020",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Max2020",
            "formatString": "0",
            "lineageTag": "dc013853-82c6-49f8-ac8e-9454343aac94",
            "summarizeBy": "none",
            "modifiedTime": "2021-03-27T20:39:50.15",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T20:37:52.25",
              "refreshedTime": "2021-04-20T15:58:07.65"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2021-03-27T20:39:47.646667"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Età-135facf0-08df-4c7d-9224-596d93b0d3ac",
            "mode": "import",
            "state": "ready",
            "modifiedTime": "2021-04-20T11:01:05.566667",
            "refreshedTime": "2021-04-20T15:58:07.63",
            "source": {
              "type": "m",
              "expression": "let\n    Source = #\"anagrafica-vaccini-summary-latest\",\n    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"fascia_anagrafica\"}),\n    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\"),\n    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Duplicates\",{{\"fascia_anagrafica\", \"Età\"}}),\n    #\"Added Custom\" = Table.AddColumn(#\"Renamed Columns\", \"FasciaAnagrafica\", each [Età]),\n    #\"Reordered Columns\" = Table.ReorderColumns(#\"Added Custom\",{\"FasciaAnagrafica\", \"Età\"}),\n    #\"Changed Type\" = Table.TransformColumnTypes(#\"Reordered Columns\",{{\"FasciaAnagrafica\", type text}}),\n    #\"Inserted First Characters\" = Table.AddColumn(#\"Changed Type\", \"Min\", each Text.Start([FasciaAnagrafica], 2), type text),\n    #\"Added Custom Column\" = Table.AddColumn(#\"Inserted First Characters\", \"Max\", each let splitFasciaAnagrafica = Splitter.SplitTextByDelimiter(\"-\", QuoteStyle.None)([FasciaAnagrafica]) in Text.Combine({Text.Start([FasciaAnagrafica], 1), Text.Reverse(Text.Middle(Text.Reverse(splitFasciaAnagrafica{0}?), 2)), \"9\"}), type text),\n    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Custom Column\",{{\"Min\", Int64.Type}, {\"Max\", Int64.Type}}),\n    #\"Inserted Subtraction\" = Table.AddColumn(#\"Changed Type1\", \"Min2020\", each [Min] - 1, type number),\n    #\"Inserted Subtraction1\" = Table.AddColumn(#\"Inserted Subtraction\", \"Max2020\", each [Max] - 1, type number),\n    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Inserted Subtraction1\",{{\"Min2020\", Int64.Type}, {\"Max2020\", Int64.Type}}),\n    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type2\",{\"Min\", \"Max\"})\nin\n    #\"Removed Columns\""
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table",
            "modifiedTime": "2021-03-27T18:03:55.973333"
          }
        ]
      },
      {
        "name": "Categoria",
        "lineageTag": "11b1a7a9-1280-45b0-957b-3631bd66d207",
        "modifiedTime": "2021-03-27T18:03:55.97",
        "structureModifiedTime": "2021-03-27T18:03:55.97",
        "columns": [
          {
            "type": "rowNumber",
            "name": "RowNumber-2662979B-1795-4F74-8F37-6A1BA8059B61",
            "dataType": "int64",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "isNullable": false,
            "modifiedTime": "2021-03-27T18:03:55.973333",
            "structureModifiedTime": "2021-03-27T18:03:55.97",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T18:04:01.296667",
              "refreshedTime": "2021-04-20T15:58:07.263333"
            }
          },
          {
            "name": "CodiceCategoria",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CodiceCategoria",
            "lineageTag": "017a1bf6-30c3-4c99-b192-2af2f844bbd7",
            "summarizeBy": "none",
            "modifiedTime": "2021-03-27T18:03:55.973333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T18:04:01.296667",
              "refreshedTime": "2021-04-20T15:58:07.263333"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T18:03:55.973333"
              }
            ]
          },
          {
            "name": "Categoria",
            "dataType": "string",
            "sourceColumn": "Categoria",
            "sortByColumn": "Ordine",
            "lineageTag": "61810d6c-d67f-44f4-b340-80db9845798e",
            "summarizeBy": "none",
            "modifiedTime": "2021-03-27T22:51:39.066667",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T18:04:01.296667",
              "refreshedTime": "2021-04-20T15:58:07.263333"
            },
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T18:03:55.973333"
              }
            ]
          },
          {
            "name": "Ordine",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ordine",
            "formatString": "0",
            "lineageTag": "e78ee30e-4590-4af6-accc-f359662ae392",
            "summarizeBy": "none",
            "modifiedTime": "2021-03-27T18:03:55.973333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T18:04:01.296667",
              "refreshedTime": "2021-04-20T15:58:07.263333"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T18:03:55.973333"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Categoria-8148c626-9197-4dd1-854d-e4410f1dc674",
            "mode": "import",
            "state": "ready",
            "modifiedTime": "2021-04-20T15:57:58.51",
            "refreshedTime": "2021-04-20T15:58:07.26",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"dZA9D8IgEIb/CmG2CfUD7OjiqtHRNORCsCGpXAPEwV/vYWxtSZx4Px4uHLcbN5Bsh8GBxsEGSCR1BO8SZIHG4ej4ip9GhM3Cmrer+RxiInrorfbop1lI5HlsGDVs3qhiBvQp5PzwPWtRABgHl5wOEfKzPoZdrgcy65J82rAXmSLBPmpTIHcML6shPCih+pgtm+z+737RYA8xObNcbhE3xW0ptGwol6KSDQPv8xfuCkgJrTKkRKUmaFtAEbvOJvqEe4DO9Rm5fiP2iyRv2zc=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [CodiceCategoria = _t, Categoria = _t, Ordine = _t]),\n    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"CodiceCategoria\", type text}, {\"Categoria\", type text}, {\"Ordine\", Int64.Type}})\nin\n    #\"Changed Type\""
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table",
            "modifiedTime": "2021-03-27T18:03:55.973333"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation",
            "modifiedTime": "2021-04-20T15:57:58.51"
          }
        ]
      },
      {
        "name": "Fornitore",
        "lineageTag": "ed0ef638-abc8-47ef-a435-f2c266953746",
        "modifiedTime": "2021-03-27T18:03:55.97",
        "structureModifiedTime": "2021-03-27T18:03:55.97",
        "columns": [
          {
            "type": "rowNumber",
            "name": "RowNumber-2662979B-1795-4F74-8F37-6A1BA8059B61",
            "dataType": "int64",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "isNullable": false,
            "modifiedTime": "2021-03-27T18:03:55.973333",
            "structureModifiedTime": "2021-03-27T18:03:55.97",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T18:04:01.42",
              "refreshedTime": "2021-04-20T15:58:07.66"
            }
          },
          {
            "name": "CodiceFornitore",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CodiceFornitore",
            "lineageTag": "88fa435d-64b5-44fe-a85e-c21712476af3",
            "summarizeBy": "none",
            "modifiedTime": "2021-03-27T18:03:55.973333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T18:04:01.416667",
              "refreshedTime": "2021-04-20T15:58:07.65"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T18:03:55.973333"
              }
            ]
          },
          {
            "name": "Fornitore",
            "dataType": "string",
            "sourceColumn": "Fornitore",
            "lineageTag": "1a3e8040-7d3c-4f3e-aa15-983587ff4d4a",
            "summarizeBy": "none",
            "modifiedTime": "2021-03-27T18:03:55.973333",
            "structureModifiedTime": "2021-03-27T18:03:55.973333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T18:04:01.416667",
              "refreshedTime": "2021-04-20T15:58:07.646667"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T18:03:55.973333"
              }
            ]
          },
          {
            "name": "Dosi",
            "dataType": "int64",
            "sourceColumn": "Dosi",
            "formatString": "0",
            "lineageTag": "c2370300-6317-4a72-80d4-73f9676ebb3d",
            "summarizeBy": "none",
            "modifiedTime": "2021-03-27T18:03:55.973333",
            "structureModifiedTime": "2021-03-27T18:03:55.973333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T18:04:01.416667",
              "refreshedTime": "2021-04-20T15:58:07.646667"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2021-03-27T18:03:55.973333"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Fornitore-bc2417b5-bd4c-4be8-a038-d76860109eab",
            "mode": "import",
            "state": "ready",
            "modifiedTime": "2021-04-20T11:01:05.566667",
            "refreshedTime": "2021-04-20T15:58:07.63",
            "source": {
              "type": "m",
              "expression": "let\n    Source = #\"consegne-vaccini-latest\",\n    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"fornitore\"}),\n    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\"),\n    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Duplicates\",{{\"fornitore\", \"CodiceFornitore\"}}),\n    #\"Merged Queries\" = Table.NestedJoin(#\"Renamed Columns\", {\"CodiceFornitore\"}, DosiFornitore, {\"CodiceFornitore\"}, \"DosiFornitore\", JoinKind.LeftOuter),\n    #\"Expanded DosiFornitore\" = Table.ExpandTableColumn(#\"Merged Queries\", \"DosiFornitore\", {\"Fornitore\", \"Dosi\"}, {\"DosiFornitore.Fornitore\", \"DosiFornitore.Dosi\"}),\n    #\"Added Custom\" = Table.AddColumn(#\"Expanded DosiFornitore\", \"Fornitore\", each [DosiFornitore.Fornitore] ?? [CodiceFornitore]),\n    #\"Added Custom1\" = Table.AddColumn(#\"Added Custom\", \"Dosi\", each [DosiFornitore.Dosi] ?? 2),\n    #\"Removed Columns\" = Table.RemoveColumns(#\"Added Custom1\",{\"DosiFornitore.Fornitore\", \"DosiFornitore.Dosi\"}),\n    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Columns\",{{\"Fornitore\", type text}, {\"Dosi\", Int64.Type}})\nin\n    #\"Changed Type\""
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table",
            "modifiedTime": "2021-03-27T18:03:55.973333"
          }
        ]
      },
      {
        "name": "Consegne",
        "lineageTag": "3c675336-a9d1-48c1-8d18-279162aa8543",
        "modifiedTime": "2021-03-27T18:03:55.97",
        "structureModifiedTime": "2021-03-30T16:24:07.943333",
        "columns": [
          {
            "type": "rowNumber",
            "name": "RowNumber-2662979B-1795-4F74-8F37-6A1BA8059B61",
            "dataType": "int64",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "isNullable": false,
            "modifiedTime": "2021-03-27T18:03:55.973333",
            "structureModifiedTime": "2021-03-27T18:03:55.97",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T18:04:01.26",
              "refreshedTime": "2021-04-20T15:58:06.69"
            }
          },
          {
            "name": "CodiceArea",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CodiceArea",
            "lineageTag": "1ae1ff73-f83c-4a2b-b275-66ca68ce20fb",
            "summarizeBy": "none",
            "modifiedTime": "2021-03-27T18:03:55.973333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T18:04:01.26",
              "refreshedTime": "2021-04-20T15:58:06.693333"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T18:03:55.973333"
              }
            ]
          },
          {
            "name": "CodiceFornitore",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CodiceFornitore",
            "lineageTag": "59846c9c-5dbe-4a67-a2c6-7c8798c134de",
            "summarizeBy": "none",
            "modifiedTime": "2021-03-27T18:03:55.973333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T18:04:01.26",
              "refreshedTime": "2021-04-20T15:58:06.693333"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T18:03:55.973333"
              }
            ]
          },
          {
            "name": "Dosi",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Dosi",
            "formatString": "0",
            "lineageTag": "9059ac1b-b985-46e7-adde-4243e99bb64d",
            "summarizeBy": "none",
            "modifiedTime": "2021-03-27T18:17:12.926667",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T18:04:01.26",
              "refreshedTime": "2021-04-20T15:58:06.693333"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2021-03-27T18:03:55.973333"
              }
            ]
          },
          {
            "name": "Data",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Data",
            "formatString": "Long Date",
            "lineageTag": "571eac2a-19de-412b-a22d-1293ac03975d",
            "summarizeBy": "none",
            "modifiedTime": "2022-04-04T14:30:13.833333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T18:04:01.26",
              "refreshedTime": "2021-04-20T15:58:06.693333"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T18:03:55.973333"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date",
                "modifiedTime": "2021-03-27T18:03:55.973333"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Consegne-162d318c-7b10-4f42-a79d-631e90db97d2",
            "mode": "import",
            "state": "ready",
            "modifiedTime": "2021-04-20T11:01:05.566667",
            "refreshedTime": "2021-04-20T15:58:06.686667",
            "source": {
              "type": "m",
              "expression": "let\n    Source = #\"consegne-vaccini-latest\",\n    #\"Removed Columns\" = Table.RemoveColumns(Source,{\"codice_NUTS1\", \"codice_NUTS2\", \"codice_regione_ISTAT\", \"nome_area\"}),\n    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"area\", \"CodiceArea\"}, {\"fornitore\", \"CodiceFornitore\"}, {\"numero_dosi\", \"Dosi\"}, {\"data_consegna\", \"Data\"}})\nin\n    #\"Renamed Columns\""
            }
          }
        ],
        "measures": [
          {
            "name": "# Dosi Consegnate",
            "description": "Numero di dosi consegnate.",
            "expression": "\nIF (\n    NOT ISFILTERED ( 'Età' ) && NOT ISFILTERED ( Categoria ) && NOT ISFILTERED ( Genere ),\n    SUM ( Consegne[Dosi] )\n)",
            "formatString": "#,0",
            "lineageTag": "6b43963b-8d3b-422e-9724-f9ed41b00d6b",
            "dataType": "int64",
            "modifiedTime": "2021-04-10T17:29:29.5",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "# Dosi in Magazzino",
            "description": "Numero di dosi disponibili in magazzino da somministrare.",
            "expression": "\nIF (\n    NOT ISFILTERED ( 'Età' ) && NOT ISFILTERED ( Categoria ) && NOT ISFILTERED ( Genere ),\n    VAR LastVisibleDate = \n        MIN ( \n            MAX ( MAX ( Somministrazioni[Data] ), MAX ( Consegne[Data] ) ),\n            MAX ( Data[Data] )\n        )\n    VAR Result = \n        CALCULATE (\n            [# Dosi Consegnate] - [# Dosi Somministrate],\n            'Data'[Data] <= LastVisibleDate\n        )\n    RETURN Result\n)",
            "formatString": "#,0",
            "lineageTag": "254490bc-d47d-4ac9-b140-3361cf449994",
            "dataType": "int64",
            "modifiedTime": "2021-04-10T17:29:47.013333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "% Dosi Somministrate",
            "description": "Percentuale di dosi somministrate rispetto alle dosi consegnate.\n",
            "expression": "DIVIDE ( [# Dosi Somministrate], [# Dosi Consegnate] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "3a01cfab-9859-4881-8320-83164542d647",
            "dataType": "double",
            "modifiedTime": "2021-04-12T14:21:16.016667",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "# Tot. Dosi Consegnate",
            "description": "Numero totale di dosi consegnate dall'inizio della campagna di vaccinazione.",
            "expression": "\nVAR LastVisibleDate = \n    MIN (\n        CALCULATE ( MAX ( Somministrazioni[Data] ) ),\n        MAX ( Data[Data] )\n    )\nVAR Result = \n    CALCULATE (\n        [# Dosi Consegnate],\n        'Data'[Data] <= LastVisibleDate\n    )\nRETURN Result\n",
            "formatString": "#,0",
            "lineageTag": "80d97690-fa25-41cf-991b-d2a94f4be58e",
            "dataType": "int64",
            "modifiedTime": "2021-04-10T17:30:07.966667",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "# Scorte (gg)",
            "description": "Durata delle scorte di magazzino (in giorni) in base alle somministrazioni dei 7 giorni precedenti.",
            "expression": "\nVAR _FilterDate = MIN ( MAX ('Data'[Data] ), TODAY() - 1)\nRETURN CALCULATE (\n    DIVIDE ( [# Dosi in Magazzino], [# Dosi / g Ultimi 7 gg] ),\n    'Data'[Data] = _FilterDate - 6 && 'Data'[Data] <= _FilterDate\n)",
            "formatString": "#,0.00",
            "lineageTag": "cbc7c437-377f-45e1-8009-39a4c749b18b",
            "dataType": "double",
            "modifiedTime": "2021-04-05T14:39:19.75",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table",
            "modifiedTime": "2021-03-27T18:03:55.973333"
          }
        ]
      },
      {
        "name": "SomministrazioniCategoria",
        "lineageTag": "59cc84a5-3208-4ea1-b5a0-320420c3d7be",
        "modifiedTime": "2021-03-27T18:03:55.97",
        "structureModifiedTime": "2021-03-27T18:03:55.97",
        "columns": [
          {
            "type": "rowNumber",
            "name": "RowNumber-2662979B-1795-4F74-8F37-6A1BA8059B61",
            "dataType": "int64",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "isNullable": false,
            "modifiedTime": "2021-03-27T18:03:55.973333",
            "structureModifiedTime": "2021-03-27T18:03:55.97",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-20T07:47:23.813333",
              "refreshedTime": "2021-04-20T15:58:07.76"
            }
          },
          {
            "name": "Data",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Data",
            "formatString": "Long Date",
            "lineageTag": "9bd756a4-0703-498c-80ac-1b0a173569ac",
            "summarizeBy": "none",
            "modifiedTime": "2022-04-04T14:30:13.833333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-20T07:47:23.813333",
              "refreshedTime": "2021-04-20T15:58:07.76"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T18:03:55.973333"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date",
                "modifiedTime": "2021-03-27T18:03:55.973333"
              }
            ]
          },
          {
            "name": "CodiceFornitore",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CodiceFornitore",
            "lineageTag": "9a9a1ebc-b8c3-451a-b30b-59fa636c15c7",
            "summarizeBy": "none",
            "modifiedTime": "2021-03-27T18:03:55.973333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-20T07:47:23.813333",
              "refreshedTime": "2021-04-20T15:58:07.76"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T18:03:55.973333"
              }
            ]
          },
          {
            "name": "CodiceArea",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CodiceArea",
            "lineageTag": "c1bce464-8a3e-4022-9b52-a6e5700e7ad8",
            "summarizeBy": "none",
            "modifiedTime": "2021-03-27T18:03:55.973333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-20T07:47:23.816667",
              "refreshedTime": "2021-04-20T15:58:07.76"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T18:03:55.973333"
              }
            ]
          },
          {
            "name": "FasciaAnagrafica",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "FasciaAnagrafica",
            "lineageTag": "5693e6da-7c46-45f6-88ac-13b444a4082d",
            "summarizeBy": "none",
            "modifiedTime": "2021-03-27T18:03:55.973333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-20T07:47:23.813333",
              "refreshedTime": "2021-04-20T15:58:07.77"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T18:03:55.973333"
              }
            ]
          },
          {
            "name": "CodiceCategoria",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CodiceCategoria",
            "lineageTag": "40423a46-d64e-4364-9588-54b8928de97f",
            "summarizeBy": "none",
            "modifiedTime": "2021-03-27T18:03:55.973333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-20T07:47:23.813333",
              "refreshedTime": "2021-04-20T15:58:07.76"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T18:03:55.973333"
              }
            ]
          },
          {
            "name": "Dosi",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Dosi",
            "formatString": "0",
            "lineageTag": "d2b13e97-9da2-4d90-bbe0-063566e643d8",
            "summarizeBy": "sum",
            "modifiedTime": "2021-04-20T07:47:22.473333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-20T07:47:23.813333",
              "refreshedTime": "2021-04-20T15:58:07.76"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-04-20T07:44:41.033333"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "SomministrazioniCategoria-79bf1d5a-f3b9-4185-a850-30c828a69e18",
            "mode": "import",
            "state": "ready",
            "modifiedTime": "2021-04-20T11:01:05.566667",
            "refreshedTime": "2021-04-20T15:58:07.756667",
            "source": {
              "type": "m",
              "expression": "let\n    Source = SomministrazioniBase,\n    #\"Removed Columns\" = Table.RemoveColumns(Source,{\"sesso_maschile\", \"sesso_femminile\", \"prima_dose\", \"seconda_dose\"}),\n    #\"Unpivoted Other Columns\" = Table.UnpivotOtherColumns(#\"Removed Columns\", {\"FasciaAnagrafica\", \"CodiceArea\", \"CodiceFornitore\", \"Data\"}, \"Attribute\", \"Value\"),\n    #\"Renamed Columns\" = Table.RenameColumns(#\"Unpivoted Other Columns\",{{\"Attribute\", \"CodiceCategoria\"}, {\"Value\", \"Dosi\"}}),\n    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Dosi\", Int64.Type}})\nin\n    #\"Changed Type\""
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table",
            "modifiedTime": "2021-03-27T18:03:55.973333"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation",
            "modifiedTime": "2021-04-20T11:01:05.566667"
          }
        ]
      },
      {
        "name": "Somministrazioni",
        "lineageTag": "bcc4d09d-b0b4-4f98-bb00-130d2fc223bc",
        "modifiedTime": "2021-03-27T18:03:55.97",
        "structureModifiedTime": "2021-04-20T11:01:05.566667",
        "columns": [
          {
            "type": "rowNumber",
            "name": "RowNumber-2662979B-1795-4F74-8F37-6A1BA8059B61",
            "dataType": "int64",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "isNullable": false,
            "modifiedTime": "2021-03-27T18:03:55.973333",
            "structureModifiedTime": "2021-03-27T18:03:55.97",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T18:04:01.42",
              "refreshedTime": "2021-04-20T15:58:06.946667"
            }
          },
          {
            "name": "Data",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Data",
            "formatString": "Long Date",
            "lineageTag": "f4241aa8-9158-4e93-8c17-fc12ce075d57",
            "summarizeBy": "none",
            "modifiedTime": "2022-04-04T14:30:13.833333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T18:04:01.42",
              "refreshedTime": "2021-04-20T15:58:06.946667"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T18:03:55.973333"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date",
                "modifiedTime": "2021-03-27T18:03:55.973333"
              }
            ]
          },
          {
            "name": "CodiceFornitore",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CodiceFornitore",
            "lineageTag": "43359b26-7824-41eb-8b20-7c2d2c7ce69e",
            "summarizeBy": "none",
            "modifiedTime": "2021-03-27T18:03:55.973333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T18:04:01.42",
              "refreshedTime": "2021-04-20T15:58:06.946667"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T18:03:55.973333"
              }
            ]
          },
          {
            "name": "CodiceArea",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CodiceArea",
            "lineageTag": "57fd20b7-8f80-41b3-aeab-742ed3507331",
            "summarizeBy": "none",
            "modifiedTime": "2021-03-27T18:03:55.973333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T18:04:01.42",
              "refreshedTime": "2021-04-20T15:58:06.946667"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T18:03:55.973333"
              }
            ]
          },
          {
            "name": "FasciaAnagrafica",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "FasciaAnagrafica",
            "lineageTag": "5cab0f93-bff9-4464-9cba-3e04c3e21dc9",
            "summarizeBy": "none",
            "modifiedTime": "2021-03-27T18:03:55.973333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T18:04:01.42",
              "refreshedTime": "2021-04-20T15:58:06.95"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T18:03:55.973333"
              }
            ]
          },
          {
            "name": "PrimaDose",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PrimaDose",
            "formatString": "0",
            "lineageTag": "f7a97819-8c76-43e7-a4cb-30c27c2331ec",
            "summarizeBy": "none",
            "modifiedTime": "2021-03-27T18:25:56.646667",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T18:04:01.423333",
              "refreshedTime": "2021-04-20T15:58:06.95"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2021-03-27T18:03:55.973333"
              }
            ]
          },
          {
            "name": "SecondaDose",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SecondaDose",
            "formatString": "0",
            "lineageTag": "534e8948-633f-44cb-bb2b-63624bb80e53",
            "summarizeBy": "none",
            "modifiedTime": "2021-03-27T18:25:58.863333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T18:04:01.423333",
              "refreshedTime": "2021-04-20T15:58:06.946667"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2021-03-27T18:03:55.973333"
              }
            ]
          },
          {
            "name": "categoria_60_69",
            "dataType": "string",
            "sourceColumn": "categoria_60_69",
            "lineageTag": "ef18a4c5-3d3a-4aac-a898-0f067d25c5fb",
            "summarizeBy": "none",
            "modifiedTime": "2021-04-20T07:44:41.68",
            "structureModifiedTime": "2021-04-20T07:44:41.196667",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-20T07:44:43.72",
              "refreshedTime": "2021-04-20T15:58:06.946667"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-04-20T07:44:41.196667"
              }
            ]
          },
          {
            "name": "categoria_70_79",
            "dataType": "string",
            "sourceColumn": "categoria_70_79",
            "lineageTag": "be40c1d1-b38c-42f2-884f-00e8e89cadf3",
            "summarizeBy": "none",
            "modifiedTime": "2021-04-20T07:44:41.68",
            "structureModifiedTime": "2021-04-20T07:44:41.286667",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-20T07:44:43.706667",
              "refreshedTime": "2021-04-20T15:58:06.946667"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-04-20T07:44:41.286667"
              }
            ]
          },
          {
            "name": "categoria_soggetti_fragili",
            "dataType": "string",
            "sourceColumn": "categoria_soggetti_fragili",
            "lineageTag": "47448ff4-1e8d-47b4-bd90-85384a0daf1c",
            "summarizeBy": "none",
            "modifiedTime": "2021-04-20T07:44:41.68",
            "structureModifiedTime": "2021-04-20T07:44:41.386667",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-20T07:44:43.706667",
              "refreshedTime": "2021-04-20T15:58:06.95"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-04-20T07:44:41.386667"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Somministrazioni-b75db126-2b61-49b4-9254-338cbd1ab969",
            "mode": "import",
            "state": "ready",
            "modifiedTime": "2021-04-20T11:01:05.566667",
            "refreshedTime": "2021-04-20T15:58:06.943333",
            "source": {
              "type": "m",
              "expression": "let\n    Source = SomministrazioniBase,\n    #\"Removed Columns\" = Table.RemoveColumns(Source,{\"sesso_maschile\", \"sesso_femminile\", \"categoria_operatori_sanitari_sociosanitari\", \"categoria_personale_non_sanitario\", \"categoria_ospiti_rsa\", \"categoria_over80\", \"categoria_forze_armate\", \"categoria_personale_scolastico\", \"categoria_altro\"}),\n    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"prima_dose\", \"PrimaDose\"}, {\"seconda_dose\", \"SecondaDose\"}})\nin\n    #\"Renamed Columns\""
            }
          }
        ],
        "measures": [
          {
            "name": "# Dose 1",
            "description": "Numero di somministrazioni come prima dose di vaccino.\n",
            "expression": "IF ( NOT ISFILTERED ( Categoria ) && NOT ISFILTERED ( Genere ), SUM ( Somministrazioni[PrimaDose] ) )",
            "formatString": "#,0",
            "lineageTag": "d4e12145-cf71-4ea7-ab38-f41859bd2108",
            "dataType": "int64",
            "modifiedTime": "2021-03-27T21:04:28.736667",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "# Dose 2",
            "description": "Numero di somministrazioni come seconda dose di vaccino.",
            "expression": "IF ( NOT ISFILTERED ( Categoria ) && NOT ISFILTERED ( Genere ), SUM ( Somministrazioni[SecondaDose] ) )",
            "formatString": "#,0",
            "lineageTag": "c4791443-ec6d-44e2-914a-d21998c39b1f",
            "dataType": "int64",
            "modifiedTime": "2021-03-27T21:04:17.243333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "# Attesa Dose 2",
            "description": "Numero di persone in attesa della seconda dose del vaccino.",
            "expression": "CALCULATE ( [# Dose 1] - [# Dose 2], KEEPFILTERS ( Fornitore[Dosi] = 2 ) )",
            "formatString": "#,0",
            "lineageTag": "e12bb63b-9a14-4bff-b9ae-00ba74bde952",
            "dataType": "int64",
            "modifiedTime": "2021-03-27T21:03:50.25",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "# Vaccinati",
            "description": "Numero di persone completamente vaccinate. A seconda del fornitore si considerano 1 o 2 dosi per completare la vaccinazione.",
            "expression": "CALCULATE ( [# Dose 1], Fornitore[Dosi] = 1 ) + CALCULATE ( [# Dose 2], Fornitore[Dosi] = 2 )",
            "formatString": "#,0",
            "lineageTag": "2ab55e95-05e3-45e2-9bc0-57efc91c3d89",
            "dataType": "int64",
            "modifiedTime": "2021-03-27T21:06:11.016667",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "# Popolazione",
            "description": "Popolazione al 1 gennaio 2020 con età riportata alle fasce anagrafiche nel 2021. Totale include solo maggiori 16 anni. Fonte ISTAT.",
            "expression": "\nIF (\n    NOT ISFILTERED ( Categoria ),\n    CALCULATE (\n        SUM ( 'Popolazione 2020'[Popolazione] ),\n        'Età' -- Considera solo fasce di età definite nel modello\n    )\n)",
            "formatString": "#,0",
            "lineageTag": "7d0f92a1-b89d-454c-87e4-9c6973d42895",
            "dataType": "int64",
            "modifiedTime": "2021-03-27T21:23:27.7",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "% Vaccinati",
            "description": "Percentuale della popolazione (16+) completamente vaccinata. A seconda del fornitore si considerano 1 o 2 dosi per completare la vaccinazione.",
            "expression": "\nCALCULATE (\n    DIVIDE ( [# Vaccinati], [# Popolazione] ),\n    Aggregazione[Aggregazione] = \"Totale cumulato\"\n)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "cf0a5ea7-dbe5-4c79-af2c-08b5d232bfef",
            "dataType": "double",
            "modifiedTime": "2021-04-12T14:21:16.016667",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "% Attesa Dose 2",
            "description": "Percentuale della popolazione (16+) in attesa della seconda dose di vaccino.",
            "expression": "DIVIDE ( [# Attesa Dose 2], [# Popolazione] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "9b6114e8-b416-4fc9-8aac-122fb5b18c31",
            "dataType": "double",
            "modifiedTime": "2021-04-12T14:21:16.016667",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "# Non Vaccinati",
            "description": "Popolazione che non ha ricevuto nessuna dose di vaccino.",
            "expression": "IF ( NOT ISBLANK ( [# Vaccinati] ), [# Popolazione] - [# Vaccinati] - [# Attesa Dose 2] )",
            "formatString": "#,0",
            "lineageTag": "9712dff8-2c44-4554-8cf5-745417e99aae",
            "dataType": "int64",
            "modifiedTime": "2021-03-27T21:05:10.11",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "% Non Vaccinati",
            "description": "Percentuale della popolazione (16+) non vaccinata.",
            "expression": "DIVIDE ( [# Non Vaccinati], [# Popolazione] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "871e52d8-017c-45b4-89fe-9adf79f2373a",
            "dataType": "double",
            "modifiedTime": "2021-04-12T14:21:16.016667",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "# Dosi Somministrate",
            "description": "Numero totale di dosi somministrate (prima o seconda dose). Una persona può ricevere più dosi.",
            "expression": "\nSWITCH ( \n    TRUE,\n    ISFILTERED ( Categoria ) && NOT ISFILTERED ( Genere ), SUM ( SomministrazioniCategoria[Dosi] ),\n    ISFILTERED ( Genere ) && NOT ISFILTERED ( Categoria ), SUM ( SomministrazioniGenere[Dosi] ),\n    [# Dose 1] + [# Dose 2]\n)",
            "formatString": "#,0",
            "lineageTag": "5ca4f735-d015-4668-9f1a-6a7b745f2d4e",
            "dataType": "int64",
            "modifiedTime": "2021-03-27T21:04:54.88",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "# Vaccinati (1+ dosi)",
            "description": "Numero di persone parzialmente o completamente vaccinate.\n",
            "expression": "[# Vaccinati] + [# Attesa Dose 2]",
            "formatString": "#,0",
            "lineageTag": "c5c97deb-8ab1-4fc5-b67a-550ae2ffbdf2",
            "dataType": "int64",
            "modifiedTime": "2021-03-27T21:06:32.62",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "% Vaccinati (1+ dosi)",
            "description": "Percentuale di popolazione (16+) parzialmente o completamente vaccinata.",
            "expression": "\nCALCULATE (\n    DIVIDE ( [# Vaccinati (1+ dosi)], [# Popolazione] ),\n    Aggregazione[Aggregazione] = \"Totale cumulato\"\n)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "cda63070-5db4-4c99-9c9a-dd6071b48e0c",
            "dataType": "double",
            "modifiedTime": "2021-04-12T14:21:16.016667",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "# Tot. Dosi Somministrate",
            "description": "Numero totale di dosi somministrate.",
            "expression": "\nVAR LastVisibleDate = \n    MIN (\n        CALCULATE ( MAX ( Somministrazioni[Data] ) ),\n        MAX ( Data[Data] )\n    )\nVAR Result = \n    CALCULATE (\n        [# Dosi Somministrate],\n        'Data'[Data] <= LastVisibleDate\n    )\nRETURN Result\n",
            "formatString": "#,0",
            "lineageTag": "056f109f-882e-4b9e-930a-5f0006ac4dfd",
            "dataType": "int64",
            "modifiedTime": "2021-04-10T17:37:38.46",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "% Dosi / Popolazione",
            "description": "Percentuali di dosi somministrate rispetto alla popolazione (16+) di riferimento.",
            "expression": "DIVIDE ( [# Dosi Somministrate], [# Popolazione] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "b5f37535-f52f-454d-bf85-9808c4ddab69",
            "dataType": "double",
            "modifiedTime": "2021-04-12T14:21:16.016667",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Data Aggiornamento",
            "description": "Data ultimo aggiornamento dati.",
            "expression": "CALCULATE ( MAX ( Somministrazioni[Data] ), REMOVEFILTERS() )",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "e9db5447-ed51-4f3d-90a0-54b1806df507",
            "dataType": "dateTime",
            "modifiedTime": "2021-04-10T17:39:13.43",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}",
                "modifiedTime": "2022-04-04T14:30:13.833333"
              }
            ]
          },
          {
            "name": "Label Data Aggiornamento",
            "description": "Testo descrittivo della data di ultimo aggiornamento dati.",
            "expression": "\"Dati aggiornati al \" & FORMAT ( [Data Aggiornamento], \"dd/mm/yy\" )",
            "lineageTag": "dd8d1b70-84f1-46aa-96a4-008d20b704e3",
            "dataType": "string",
            "modifiedTime": "2021-04-10T17:40:55.693333",
            "structureModifiedTime": "2021-03-29T16:17:08.57"
          },
          {
            "name": "# Dosi / g Ultimi 7 gg",
            "description": "Media giornaliera aggiornata di somministrazioni (indipendendemente da dose 1 o 2), basata sugli ultimi 7 giorni, indipendentemente dalla data selezionata.",
            "expression": "\nVAR _MaxDateAvailable = CALCULATE ( MAX ( Somministrazioni[Data] ) - 1, REMOVEFILTERS() )\nRETURN CALCULATE ( [# Dosi / Giorno Somministrate (7 gg)], 'Data'[Data] = _MaxDateAvailable )",
            "formatString": "#,0.00",
            "lineageTag": "44f3839e-11bc-4be5-8f5f-ccdeaf754d79",
            "dataType": "double",
            "modifiedTime": "2021-04-10T17:36:35.183333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "# Dosi / g 7 gg Prec.",
            "description": "Media giornaliera aggiornata di somministrazioni (indipendendemente da dose 1 o 2), basata sui 7 giorni precedenti agli ultimi 7 giorni, indipendentemente dalla data selezionata.",
            "expression": "\nVAR _MaxDateAvailable = CALCULATE ( MAX ( Somministrazioni[Data] ) - 1, REMOVEFILTERS() )\nRETURN CALCULATE ( [# Dosi / Giorno Somministrate (7 gg)], 'Data'[Data] = _MaxDateAvailable - 7)",
            "formatString": "#,0.00",
            "lineageTag": "892c7cfb-53e9-497f-a98c-843c13388d6a",
            "dataType": "double",
            "modifiedTime": "2021-04-10T17:37:03.193333",
            "structureModifiedTime": "2021-03-30T15:19:57.096667"
          },
          {
            "name": "Descrizione Dosi 7 gg",
            "description": "Testo descrittivo del periodo degli ultimi 7 giorni di riferimento per gli indicatori Dosi/g.",
            "expression": "\nVAR _MaxDate = CALCULATE ( MAX ( Somministrazioni[Data] ) - 1, REMOVEFILTERS() )\nVAR _DateStart = FORMAT ( _MaxDate - 6, \"dd/mm\" )\nVAR _DateEnd = FORMAT ( _MaxDate, \"dd/mm\" )\nVAR _RefDateStart = FORMAT ( _MaxDate - 13, \"dd/mm\" )\nVAR _RefDateEnd = FORMAT ( _MaxDate - 7, \"dd/mm\" )\nRETURN \"Somministrazioni medie giornaliere\" & UNICHAR(10) & _DateStart & \"-\" & _DateEnd & \" vs. \" & _RefDateStart & \"-\" & _RefDateEnd ",
            "lineageTag": "6e478575-810a-45a0-a2ad-5df95cdf3c21",
            "dataType": "string",
            "modifiedTime": "2021-04-20T15:50:09.983333",
            "structureModifiedTime": "2021-03-30T16:07:44.316667"
          },
          {
            "name": "# Dosi / Giorno Somministrate (7 gg)",
            "description": "Media giornaliera di somministrazioni (indipendendemente da dose 1 o 2), basata sui 7 giorni precedenti.",
            "expression": "\nVAR _DaysAverage = 7\nVAR _MinDateAvailable = CALCULATE ( MIN ( Somministrazioni[Data] ), REMOVEFILTERS() )\nVAR _MaxDateAvailable = CALCULATE ( MAX ( Somministrazioni[Data] ) - 1, REMOVEFILTERS() )\nVAR _MaxDate = MAX ( 'Data'[Data] )\nVAR Result = \nIF ( \n    _MaxDate <= _MaxDateAvailable && (_MaxDate - _DaysAverage) >= _MinDateAvailable,\n    CALCULATE (\n        DIVIDE ( [# Dosi Somministrate], _DaysAverage ),\n        DATESINPERIOD ( 'Data'[Data], MAX ( 'Data'[Data] ), -_DaysAverage, DAY )\n    )\n)\nRETURN Result",
            "formatString": "#,0",
            "lineageTag": "36eef6f1-ddd4-4540-a8a8-837adc5aea32",
            "dataType": "double",
            "modifiedTime": "2021-04-10T17:37:16.556667",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "# Dose 2 / Giorno Somministrate (7gg)",
            "description": "Media giornaliera di somministrazioni come seconda dose di vaccino, basata sui 7 giorni precedenti.",
            "expression": "\nVAR _DaysAverage = 7\nVAR _MinDateAvailable = CALCULATE ( MIN ( Somministrazioni[Data] ), REMOVEFILTERS() )\nVAR _MaxDateAvailable = CALCULATE ( MAX ( Somministrazioni[Data] ) - 1, REMOVEFILTERS() )\nVAR _MaxDate = MAX ( 'Data'[Data] )\nVAR Result = \nIF ( \n    _MaxDate <= _MaxDateAvailable && (_MaxDate - _DaysAverage) >= _MinDateAvailable,\n    CALCULATE (\n        DIVIDE ( [# Dose 2], _DaysAverage ),\n        DATESINPERIOD ( 'Data'[Data], MAX ( 'Data'[Data] ), -_DaysAverage, DAY )\n    )\n)\nRETURN Result",
            "formatString": "#,0",
            "lineageTag": "5e6e65c9-b12d-47d1-9775-9f9e1b1f8df6",
            "dataType": "double",
            "modifiedTime": "2021-04-10T17:32:30.256667",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "# Dose 1 / Giorno Somministrate (7gg)",
            "description": "Media giornaliera di somministrazioni come prima dose di vaccino, basata sui 7 giorni precedenti.",
            "expression": "\nVAR _DaysAverage = 7\nVAR _MinDateAvailable = CALCULATE ( MIN ( Somministrazioni[Data] ), REMOVEFILTERS() )\nVAR _MaxDateAvailable = CALCULATE ( MAX ( Somministrazioni[Data] ) - 1, REMOVEFILTERS() )\nVAR _MaxDate = MAX ( 'Data'[Data] )\nVAR Result = \nIF ( \n    _MaxDate <= _MaxDateAvailable && (_MaxDate - _DaysAverage) >= _MinDateAvailable,\n    CALCULATE (\n        DIVIDE ( [# Dose 1], _DaysAverage ),\n        DATESINPERIOD ( 'Data'[Data], MAX ( 'Data'[Data] ), -_DaysAverage, DAY )\n    )\n)\nRETURN Result",
            "formatString": "#,0",
            "lineageTag": "fdeb5a75-8195-435d-9e5d-17dbc6aa9294",
            "dataType": "double",
            "modifiedTime": "2021-04-10T17:32:37.103333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table",
            "modifiedTime": "2021-03-27T18:03:55.973333"
          }
        ]
      },
      {
        "name": "SomministrazioniGenere",
        "lineageTag": "4958163b-4e03-4f78-98a0-8a1c14ab0d21",
        "modifiedTime": "2021-03-27T18:03:55.97",
        "structureModifiedTime": "2021-03-27T18:03:55.97",
        "columns": [
          {
            "type": "rowNumber",
            "name": "RowNumber-2662979B-1795-4F74-8F37-6A1BA8059B61",
            "dataType": "int64",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "isNullable": false,
            "modifiedTime": "2021-03-27T18:03:55.973333",
            "structureModifiedTime": "2021-03-27T18:03:55.97",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-20T07:47:23.37",
              "refreshedTime": "2021-04-20T15:58:07.266667"
            }
          },
          {
            "name": "Data",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Data",
            "formatString": "Long Date",
            "lineageTag": "b4077ad0-a30c-466e-b035-87e07b71f3a6",
            "summarizeBy": "none",
            "modifiedTime": "2022-04-04T14:30:13.833333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-20T07:47:23.37",
              "refreshedTime": "2021-04-20T15:58:07.253333"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T18:03:55.973333"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date",
                "modifiedTime": "2021-03-27T18:03:55.973333"
              }
            ]
          },
          {
            "name": "CodiceFornitore",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CodiceFornitore",
            "lineageTag": "91ba9f51-8eaf-4cfd-918a-1105a0f8111a",
            "summarizeBy": "none",
            "modifiedTime": "2021-03-27T18:03:55.973333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-20T07:47:23.373333",
              "refreshedTime": "2021-04-20T15:58:07.253333"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T18:03:55.973333"
              }
            ]
          },
          {
            "name": "CodiceArea",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CodiceArea",
            "lineageTag": "30834c67-851b-4e6f-809d-c3dd9a66f4b5",
            "summarizeBy": "none",
            "modifiedTime": "2021-03-27T18:03:55.973333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-20T07:47:23.37",
              "refreshedTime": "2021-04-20T15:58:07.253333"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T18:03:55.973333"
              }
            ]
          },
          {
            "name": "FasciaAnagrafica",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "FasciaAnagrafica",
            "lineageTag": "8934e776-ad11-4e03-bd3c-370d08e5587a",
            "summarizeBy": "none",
            "modifiedTime": "2021-03-27T18:17:25.503333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-20T07:47:23.373333",
              "refreshedTime": "2021-04-20T15:58:07.253333"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T18:03:55.973333"
              }
            ]
          },
          {
            "name": "CodiceGenere",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CodiceGenere",
            "lineageTag": "40ff14fa-c21a-4a84-bab0-c352133a5158",
            "summarizeBy": "none",
            "modifiedTime": "2021-03-27T18:03:55.973333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-20T07:47:23.37",
              "refreshedTime": "2021-04-20T15:58:07.253333"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T18:03:55.973333"
              }
            ]
          },
          {
            "name": "Dosi",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Dosi",
            "formatString": "0",
            "lineageTag": "2de9d6b4-b396-4edc-bd17-cf28a4548eff",
            "summarizeBy": "sum",
            "modifiedTime": "2021-04-20T07:47:22.576667",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-20T07:47:23.373333",
              "refreshedTime": "2021-04-20T15:58:07.253333"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-04-20T07:44:41.566667"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "SomministrazioniGenere-806a959a-d630-4c88-83f3-708a766093f2",
            "mode": "import",
            "state": "ready",
            "modifiedTime": "2021-04-20T15:57:58.51",
            "refreshedTime": "2021-04-20T15:58:07.246667",
            "source": {
              "type": "m",
              "expression": "let\n    Source = SomministrazioniBase,\n    #\"Removed Columns\" = Table.RemoveColumns(Source,{\"categoria_operatori_sanitari_sociosanitari\", \"categoria_60_69\", \"categoria_70_79\", \"categoria_soggetti_fragili\", \"categoria_personale_non_sanitario\", \"categoria_ospiti_rsa\", \"categoria_over80\", \"categoria_forze_armate\", \"categoria_personale_scolastico\", \"categoria_altro\", \"prima_dose\", \"seconda_dose\"}),\n    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"sesso_maschile\", \"M\"}, {\"sesso_femminile\", \"F\"}}),\n    #\"Unpivoted Other Columns\" = Table.UnpivotOtherColumns(#\"Renamed Columns\", {\"Data\", \"CodiceFornitore\", \"CodiceArea\", \"FasciaAnagrafica\"}, \"Attribute\", \"Value\"),\n    #\"Renamed Columns1\" = Table.RenameColumns(#\"Unpivoted Other Columns\",{{\"Attribute\", \"CodiceGenere\"}, {\"Value\", \"Dosi\"}}),\n    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns1\",{{\"Dosi\", Int64.Type}})\nin\n    #\"Changed Type\""
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table",
            "modifiedTime": "2021-03-27T18:03:55.973333"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation",
            "modifiedTime": "2021-04-20T15:57:58.51"
          }
        ]
      },
      {
        "name": "Area",
        "lineageTag": "8f6c4703-eb4d-495c-a892-af9b5d77dfc3",
        "modifiedTime": "2021-03-27T18:03:55.97",
        "structureModifiedTime": "2021-04-06T21:23:50.316667",
        "columns": [
          {
            "type": "rowNumber",
            "name": "RowNumber-2662979B-1795-4F74-8F37-6A1BA8059B61",
            "dataType": "int64",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "isNullable": false,
            "modifiedTime": "2021-03-27T18:03:55.973333",
            "structureModifiedTime": "2021-03-27T18:03:55.97",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T18:04:01.363333",
              "refreshedTime": "2021-04-20T15:58:06.646667"
            }
          },
          {
            "name": "CodiceArea",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CodiceArea",
            "lineageTag": "ffdceed3-abbf-489b-98bb-9cc1498efb79",
            "summarizeBy": "none",
            "modifiedTime": "2021-03-27T18:03:55.973333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T18:04:01.363333",
              "refreshedTime": "2021-04-20T15:58:06.626667"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T18:03:55.973333"
              }
            ]
          },
          {
            "name": "NUTS1",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "NUTS1",
            "lineageTag": "06bc8215-a77b-4f78-a0b4-700e26284cec",
            "summarizeBy": "none",
            "modifiedTime": "2021-03-27T18:03:55.973333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T18:04:01.363333",
              "refreshedTime": "2021-04-20T15:58:06.63"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T18:03:55.973333"
              }
            ]
          },
          {
            "name": "NUTS2",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "NUTS2",
            "lineageTag": "32b5ec12-e4d6-46e9-8e0d-1dcf428071a2",
            "summarizeBy": "none",
            "modifiedTime": "2021-03-27T18:03:55.973333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T18:04:01.363333",
              "refreshedTime": "2021-04-20T15:58:06.63"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T18:03:55.973333"
              }
            ]
          },
          {
            "name": "Macro Area",
            "dataType": "string",
            "sourceColumn": "Macro Area",
            "sortByColumn": "OrdineMacroArea",
            "lineageTag": "79fc5816-171a-456c-a7bb-e86259698ade",
            "summarizeBy": "none",
            "modifiedTime": "2021-03-27T18:03:55.973333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T18:04:01.363333",
              "refreshedTime": "2021-04-20T15:58:06.63"
            },
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T18:03:55.973333"
              }
            ]
          },
          {
            "name": "OrdineMacroArea",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "OrdineMacroArea",
            "formatString": "0",
            "lineageTag": "f13b04c6-fb11-42b1-85e5-0945238d965f",
            "summarizeBy": "none",
            "modifiedTime": "2021-03-27T18:03:55.973333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T18:04:01.363333",
              "refreshedTime": "2021-04-20T15:58:06.63"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2021-03-27T18:03:55.973333"
              }
            ]
          },
          {
            "name": "Regione",
            "dataType": "string",
            "sourceColumn": "Regione",
            "lineageTag": "6eec170f-0891-4649-9e3f-fb72003ccb49",
            "summarizeBy": "none",
            "modifiedTime": "2021-03-27T18:03:55.973333",
            "structureModifiedTime": "2021-03-27T18:03:55.973333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T18:04:01.363333",
              "refreshedTime": "2021-04-20T15:58:06.63"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T18:03:55.973333"
              }
            ]
          },
          {
            "name": "Area",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Area",
            "sortByColumn": "NUTS2",
            "lineageTag": "637a7ae3-dcc8-4d54-a9f4-15ca3735e3a6",
            "summarizeBy": "none",
            "modifiedTime": "2021-03-27T18:03:55.973333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T18:04:01.363333",
              "refreshedTime": "2021-04-20T15:58:06.63"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T18:03:55.973333"
              }
            ]
          },
          {
            "name": "CodiceRegioneIstat",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CodiceRegioneIstat",
            "formatString": "0",
            "lineageTag": "ba828bdd-7fcc-4ad4-961d-a215b215cee9",
            "summarizeBy": "none",
            "modifiedTime": "2021-04-06T21:23:57.843333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-06T21:23:50.596667",
              "refreshedTime": "2021-04-20T15:58:06.63"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-04-06T21:23:50.316667"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Area-266debe4-e018-4cf5-9031-57d8836996ec",
            "mode": "import",
            "state": "ready",
            "modifiedTime": "2021-04-20T11:01:05.566667",
            "refreshedTime": "2021-04-20T15:58:06.62",
            "source": {
              "type": "m",
              "expression": "let\n    Source = #\"punti-somministrazione-latest\",\n    #\"Removed Columns\" = Table.RemoveColumns(Source,{\"provincia\", \"comune\", \"presidio_ospedaliero\"}),\n    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Columns\"),\n    #\"Added Conditional Column\" = Table.AddColumn(#\"Removed Duplicates\", \"codice_istat\", each if [area] = \"PAB\" then 21 else if [area] = \"PAT\" then 22 else [codice_regione_ISTAT], Int32.Type ),\n    #\"Renamed Columns\" = Table.RenameColumns(#\"Added Conditional Column\",{{\"area\", \"CodiceArea\"}, {\"codice_NUTS1\", \"NUTS1\"}, {\"codice_NUTS2\", \"NUTS2\"}, {\"codice_istat\", \"CodiceRegioneIstat\"}, {\"nome_area\", \"NomeArea\"}}),\n    #\"Removed Columns2\" = Table.RemoveColumns(#\"Renamed Columns\",{\"codice_regione_ISTAT\"}),\n    #\"Merged Queries\" = Table.NestedJoin(#\"Removed Columns2\", {\"NUTS1\"}, MacroArea, {\"NUTS1\"}, \"MacroArea\", JoinKind.LeftOuter),\n    #\"Expanded MacroArea\" = Table.ExpandTableColumn(#\"Merged Queries\", \"MacroArea\", {\"Macro Area\", \"Ordine\"}, {\"Macro Area\", \"Ordine\"}),\n    #\"Renamed Columns1\" = Table.RenameColumns(#\"Expanded MacroArea\",{{\"Ordine\", \"OrdineMacroArea\"}}),\n    #\"Merged Queries1\" = Table.NestedJoin(#\"Renamed Columns1\", {\"NUTS2\"}, AreaDescrizione, {\"NUTS2\"}, \"AreaDescrizione\", JoinKind.LeftOuter),\n    #\"Expanded AreaDescrizione\" = Table.ExpandTableColumn(#\"Merged Queries1\", \"AreaDescrizione\", {\"Regione\"}, {\"Regione\"}),\n    #\"Added Custom\" = Table.AddColumn(#\"Expanded AreaDescrizione\", \"Area\", each [Regione] ?? [NomeArea]),\n    #\"Changed Type\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"Area\", type text}}),\n    #\"Removed Columns1\" = Table.RemoveColumns(#\"Changed Type\",{\"NomeArea\"})\nin\n    #\"Removed Columns1\""
            }
          }
        ],
        "measures": [
          {
            "name": "Regioni selezionate",
            "expression": "\"Regioni selezionate: \" & IF ( ISFILTERED ( Area ), CONCATENATEX ( DISTINCT ( Area[Regione] ), Area[Regione], \", \", Area[Regione], ASC ), \"TUTTE\" )",
            "lineageTag": "d7b10369-cc62-4448-95ec-8c0813b63037",
            "dataType": "string",
            "modifiedTime": "2021-03-29T22:35:41.28",
            "structureModifiedTime": "2021-03-29T22:32:28.903333"
          }
        ],
        "hierarchies": [
          {
            "name": "Area-Regione",
            "lineageTag": "008f919f-58fa-43a5-bb7e-0e7e31d0d020",
            "state": "ready",
            "modifiedTime": "2021-03-29T12:58:13.62",
            "structureModifiedTime": "2021-03-29T12:58:05.463333",
            "refreshedTime": "2021-04-20T15:58:06.63",
            "levels": [
              {
                "name": "Macro Area",
                "ordinal": 0,
                "column": "Macro Area",
                "lineageTag": "1db87781-77d6-45b2-a33b-fc6ce4078531",
                "modifiedTime": "2021-03-29T12:57:54.163333"
              },
              {
                "name": "Regione",
                "ordinal": 1,
                "column": "Area",
                "lineageTag": "e113f4c0-388d-4d81-8ccd-b82cee8a18c5",
                "modifiedTime": "2021-03-29T12:58:26.26"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table",
            "modifiedTime": "2021-03-27T18:03:55.973333"
          }
        ]
      },
      {
        "name": "Data",
        "lineageTag": "42d66d60-817f-46ca-b56d-5e0f6c0137fb",
        "dataCategory": "Time",
        "modifiedTime": "2021-03-30T15:50:27.746667",
        "structureModifiedTime": "2021-03-27T18:22:35.466667",
        "columns": [
          {
            "type": "rowNumber",
            "name": "RowNumber-2662979B-1795-4F74-8F37-6A1BA8059B61",
            "dataType": "int64",
            "isHidden": true,
            "isUnique": true,
            "isNullable": false,
            "modifiedTime": "2021-04-20T07:47:23.823333",
            "structureModifiedTime": "2021-03-27T18:04:20.773333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-20T07:47:23.826667",
              "refreshedTime": "2021-04-20T15:58:07.863333"
            }
          },
          {
            "type": "calculatedTableColumn",
            "name": "Anno",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Anno]",
            "formatString": "0",
            "lineageTag": "b2349666-56ba-4aca-86fb-4ce405e37fb8",
            "summarizeBy": "none",
            "modifiedTime": "2021-04-20T07:47:23.823333",
            "structureModifiedTime": "2021-03-27T18:06:02.87",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-20T07:47:23.826667",
              "refreshedTime": "2021-04-20T15:58:07.86"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2021-03-27T18:16:46.273333"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Mese Anno",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Mese Anno]",
            "sortByColumn": "MeseAnno",
            "lineageTag": "1ce5ee3a-f4ca-44b6-ac17-4aea101fa691",
            "summarizeBy": "none",
            "modifiedTime": "2021-04-20T07:47:23.823333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-20T07:47:23.833333",
              "refreshedTime": "2021-04-20T15:58:07.88"
            },
            "changedProperties": [
              {
                "property": "SortByColumn"
              },
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T18:06:02.913333"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "MeseAnno",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[MeseAnno]",
            "formatString": "0",
            "lineageTag": "bb6e0080-5f3b-4a49-bbbc-28b9d3214e90",
            "summarizeBy": "none",
            "modifiedTime": "2021-04-20T07:47:23.823333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-20T07:47:23.826667",
              "refreshedTime": "2021-04-20T15:58:07.866667"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2021-03-27T18:16:46.273333"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Settimana",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Settimana]",
            "sortByColumn": "SettimanaAnno",
            "lineageTag": "7fd820a7-9f8c-4e00-9a05-c24a7a0a547b",
            "summarizeBy": "none",
            "modifiedTime": "2021-04-20T07:47:23.823333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-20T07:47:23.833333",
              "refreshedTime": "2021-04-20T15:58:07.88"
            },
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T18:07:22.506667"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "SettimanaAnno",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[SettimanaAnno]",
            "formatString": "0",
            "lineageTag": "1199012b-e128-4d7f-ae1a-a0ee2f0ee26c",
            "summarizeBy": "none",
            "modifiedTime": "2021-04-20T07:47:23.823333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-20T07:47:23.826667",
              "refreshedTime": "2021-04-20T15:58:07.863333"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2021-03-27T18:16:46.273333"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Giorno",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Giorno]",
            "sortByColumn": "GiornoSettimana",
            "lineageTag": "a2790253-c79b-4025-a430-a6c49d4e5afd",
            "summarizeBy": "none",
            "modifiedTime": "2021-04-20T07:47:23.823333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-20T07:47:23.833333",
              "refreshedTime": "2021-04-20T15:58:07.866667"
            },
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T18:14:56.443333"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "GiornoSettimana",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[GiornoSettimana]",
            "formatString": "0",
            "lineageTag": "85c8b32c-e4ab-4617-85a2-7cda1c45c18e",
            "summarizeBy": "none",
            "modifiedTime": "2021-04-20T07:47:23.823333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-20T07:47:23.826667",
              "refreshedTime": "2021-04-20T15:58:07.866667"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2021-03-27T18:16:46.273333"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Mese",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Mese]",
            "sortByColumn": "MeseNumero",
            "lineageTag": "9dcdbe11-4aeb-4dc6-8536-39a3b0dff610",
            "summarizeBy": "none",
            "modifiedTime": "2021-04-20T07:47:23.823333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-20T07:47:23.826667",
              "refreshedTime": "2021-04-20T15:58:07.863333"
            },
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T18:16:02.913333"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "MeseNumero",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[MeseNumero]",
            "formatString": "0",
            "lineageTag": "76c1368f-497c-4d5e-bcfa-26e0483271a4",
            "summarizeBy": "none",
            "modifiedTime": "2021-04-20T07:47:23.823333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-20T07:47:23.826667",
              "refreshedTime": "2021-04-20T15:58:07.863333"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2021-03-27T18:16:46.273333"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Data",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isKey": true,
            "sourceColumn": "[Data]",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "4f0d2d66-bcf6-4cb7-a20e-1b9e051c053c",
            "summarizeBy": "none",
            "modifiedTime": "2021-04-20T07:47:23.823333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-20T07:47:23.826667",
              "refreshedTime": "2021-04-20T15:58:07.863333"
            },
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T18:18:48.266667"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}",
                "modifiedTime": "2022-04-04T14:30:13.833333"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Fine Settimana",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "expression": "CALCULATE ( MAX ( Data[Data] ), ALLEXCEPT ( Data, Data[SettimanaAnno] ) )",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "65063fcc-0e7e-40bc-b988-2de798822f61",
            "summarizeBy": "none",
            "modifiedTime": "2021-04-20T07:47:23.83",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "2021-04-20T15:58:07.863333",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-20T07:47:23.83",
              "refreshedTime": "2021-04-20T15:58:07.866667"
            },
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T18:20:38.8"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}",
                "modifiedTime": "2022-04-04T14:30:13.833333"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Fine Mese",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "expression": "CALCULATE ( MAX ( Data[Data] ), ALLEXCEPT ( Data, Data[MeseAnno] ) )",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "07a69ffa-d728-4b72-a74b-414872330640",
            "summarizeBy": "none",
            "modifiedTime": "2021-04-20T07:47:23.83",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "2021-04-20T15:58:07.866667",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-20T07:47:23.83",
              "refreshedTime": "2021-04-20T15:58:07.87"
            },
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T18:22:35.53"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}",
                "modifiedTime": "2022-04-04T14:30:13.833333"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Data-abc9cf27-87ea-42e5-b664-6ab145e843bf",
            "mode": "import",
            "state": "ready",
            "modifiedTime": "2021-04-20T07:47:23.823333",
            "refreshedTime": "2021-04-20T15:58:07.86",
            "source": {
              "type": "calculated",
              "expression": "\nVAR FirstDayOfWeek = 1 -- Use: 0 - Sunday, 1 - Monday, 2 - Tuesday, ... 5 - Friday, 6 - Saturday\nVAR FirstSundayReference = DATE ( 1900, 12, 30 ) -- Do not change this \nVAR FirstWeekReference = FirstSundayReference + FirstDayOfWeek\nVAR WeekDayCalculationType =\n    IF ( FirstDayOfWeek = 0, 7, FirstDayOfWeek ) + 10\nRETURN GENERATE (\n    SELECTCOLUMNS ( CALENDARAUTO(), \"Data\", [Date] ),\n    VAR CalDate = [Data]\n    VAR YearWeekNumber =\n        INT ( DIVIDE ( CalDate - FirstWeekReference, 7 ) )\n    RETURN ROW (\n        \"Anno\", YEAR ( CalDate ),\n        \"Mese Anno\", FORMAT ( CalDate, \"mmm yy\" ),\n        \"MeseAnno\", YEAR ( CalDate ) * 12 + MONTH ( CalDate ),\n        \"SettimanaAnno\", YearWeekNumber,\n        \"Settimana\", \"W \" & FORMAT ( WEEKNUM ( CalDate, WeekDayCalculationType ), \"00\" ) & FORMAT ( CalDate, \"-yy\" ),\n        \"Giorno\", FORMAT ( CalDate, \"ddd\" ),\n        \"GiornoSettimana\", WEEKDAY ( CalDate, WeekDayCalculationType ),\n        \"Mese\", FORMAT ( CalDate, \"mmm\" ),\n        \"MeseNumero\", MONTH ( CalDate )\n    )\n)"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Mensile",
            "lineageTag": "ee4db2b5-a102-402c-a9dc-85348111516a",
            "state": "ready",
            "modifiedTime": "2021-04-20T07:47:23.833333",
            "structureModifiedTime": "2021-03-27T18:23:31.686667",
            "refreshedTime": "2021-04-20T15:58:07.883333",
            "levels": [
              {
                "name": "Anno",
                "ordinal": 0,
                "column": "Anno",
                "lineageTag": "49f489aa-e294-40b4-b767-e881fb8c5c5b",
                "modifiedTime": "2021-03-27T18:19:19.066667"
              },
              {
                "name": "Mese",
                "ordinal": 1,
                "column": "Mese Anno",
                "lineageTag": "51ffb158-f0c1-4ce8-ba9f-637f4fb36c83",
                "modifiedTime": "2021-03-27T18:23:18.906667"
              },
              {
                "name": "Data",
                "ordinal": 2,
                "column": "Data",
                "lineageTag": "4ab38719-1c65-4d58-8cac-bdd62acdea35",
                "modifiedTime": "2021-03-27T18:23:31.686667"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "c0994fc57fb4477db43a8fa311b03f29",
            "modifiedTime": "2021-03-27T18:04:20.946667"
          }
        ]
      },
      {
        "name": "Popolazione 2020",
        "isHidden": true,
        "lineageTag": "8b5abce3-0e3f-4a1c-9f62-3d077e706c37",
        "modifiedTime": "2021-03-27T20:38:48.73",
        "structureModifiedTime": "2023-03-28T13:46:53.803333",
        "columns": [
          {
            "type": "rowNumber",
            "name": "RowNumber-2662979B-1795-4F74-8F37-6A1BA8059B61",
            "dataType": "int64",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "isNullable": false,
            "modifiedTime": "2021-03-27T20:37:51.923333",
            "structureModifiedTime": "2021-03-27T20:37:51.923333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T20:37:52.323333",
              "refreshedTime": "2021-04-20T15:58:06.696667"
            }
          },
          {
            "name": "CodiceGenere",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CodiceGenere",
            "lineageTag": "e9cc9c7a-f7e9-4cc8-b2b5-e89748ba20d6",
            "summarizeBy": "none",
            "modifiedTime": "2021-03-27T20:38:48.73",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T20:37:52.323333",
              "refreshedTime": "2021-04-20T15:58:06.696667"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T20:37:51.923333"
              }
            ]
          },
          {
            "name": "Eta 2020",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Eta 2020",
            "formatString": "0",
            "lineageTag": "64ca1206-f8e7-49b4-b9b4-f3d091da7733",
            "summarizeBy": "none",
            "modifiedTime": "2021-03-27T20:38:48.73",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T20:37:52.323333",
              "refreshedTime": "2021-04-20T15:58:06.696667"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2021-03-27T20:38:31.783333"
              }
            ]
          },
          {
            "name": "Popolazione",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Popolazione",
            "formatString": "0",
            "lineageTag": "4835c96a-fb52-4e1a-a22b-33d0cf9a0e38",
            "summarizeBy": "none",
            "modifiedTime": "2021-03-27T20:38:48.73",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T20:37:52.323333",
              "refreshedTime": "2021-04-20T15:58:06.696667"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2021-03-27T20:38:31.783333"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "FasciaAnagrafica",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "\nVAR _Eta = 'Popolazione 2020'[Eta 2020]\nRETURN \nCALCULATE (\n    DISTINCT ( 'Età'[FasciaAnagrafica] ),\n    FILTER ( 'Età', 'Età'[Min2020] <= _Eta && 'Età'[Max2020] >= _Eta )\n)",
            "lineageTag": "d5d7cc4e-bcfd-4fd1-bdca-95f269e639ed",
            "summarizeBy": "none",
            "modifiedTime": "2021-03-27T20:43:35.566667",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "2021-04-20T15:58:07.663333",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T20:43:35.566667",
              "refreshedTime": "2021-04-20T15:58:07.666667"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T20:40:05.863333"
              }
            ]
          },
          {
            "name": "NUTS2",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "NUTS2",
            "lineageTag": "77130edd-a196-41b4-bfa5-2562d2180e25",
            "summarizeBy": "none",
            "modifiedTime": "2021-03-27T22:01:18.253333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T21:59:04.23",
              "refreshedTime": "2021-04-20T15:58:06.696667"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-27T21:59:03.936667"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Popolazione 2020-a287029f-0636-428c-8f22-dc55bd451dad",
            "mode": "import",
            "state": "ready",
            "modifiedTime": "2021-04-20T11:01:05.566667",
            "refreshedTime": "2021-04-20T15:58:06.693333",
            "source": {
              "type": "m",
              "expression": "let\n\n    #\"Appended Query\" = Table.Combine({Popolazione1, Popolazione2, Popolazione3, Popolazione4, Popolazione5, Popolazione6}),\n    #\"Renamed Columns\" = Table.RenameColumns(#\"Appended Query\",{{\"NUTS2\", \"NUTS2_tofix\"}}),\n    #\"Added Custom\" = Table.AddColumn(#\"Renamed Columns\", \"NUTS2\", each if Text.Middle([NUTS2_tofix],0,3) = \"ITE\" \nthen \"ITI\" & Text.Middle([NUTS2_tofix],3)\nelse if Text.Middle([NUTS2_tofix],0,3) = \"ITD\" \nthen \"ITH\" & Text.Middle([NUTS2_tofix],3)\nelse [NUTS2_tofix]),\n    #\"Removed Columns\" = Table.RemoveColumns(#\"Added Custom\",{\"NUTS2_tofix\"}),\n    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Columns\",{{\"NUTS2\", type text}})\nin\n    #\"Changed Type\""
            }
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table",
            "modifiedTime": "2021-03-27T20:37:51.923333"
          }
        ]
      },
      {
        "name": "Aggregazione",
        "lineageTag": "94e13de4-f8d8-44f5-8d08-14c79e73ab5e",
        "modifiedTime": "2021-03-27T22:35:18.433333",
        "structureModifiedTime": "2021-03-27T22:13:58.67",
        "calculationGroup": {
          "modifiedTime": "2021-03-27T22:13:58.673333",
          "calculationItems": [
            {
              "name": "Periodo selezionato",
              "expression": "SELECTEDMEASURE()",
              "modifiedTime": "2021-03-27T22:13:58.673333"
            },
            {
              "name": "Totale cumulato",
              "expression": "IF(\n    ISSELECTEDMEASURE( [# Deceduti], [# Ingressi Terapia Intensiva] ),\n    SELECTEDMEASURE(),\n    VAR LastVisibleDate =\n    MIN(\n        CALCULATE( MAX( Somministrazioni[Data] ) ),\n        MAX( Data[Data] )\n    )\n    VAR Result =\n    CALCULATE(\n        SELECTEDMEASURE(),\n        'Data'[Data] <= LastVisibleDate\n    )\n    RETURN\n    Result\n)",
              "modifiedTime": "2021-04-06T22:20:43.43"
            }
          ]
        },
        "columns": [
          {
            "type": "rowNumber",
            "name": "RowNumber-2662979B-1795-4F74-8F37-6A1BA8059B61",
            "dataType": "int64",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "isNullable": false,
            "modifiedTime": "2021-03-27T22:14:53.953333",
            "structureModifiedTime": "2021-03-27T22:13:58.673333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T22:14:53.953333",
              "refreshedTime": "2021-03-27T22:14:53.953333"
            }
          },
          {
            "name": "Aggregazione",
            "dataType": "string",
            "sourceColumn": "Name",
            "sortByColumn": "Ordinal",
            "lineageTag": "6e1b8244-b0dc-4ffc-8a39-14a36d5f5e92",
            "summarizeBy": "none",
            "modifiedTime": "2021-03-30T12:16:17.7",
            "structureModifiedTime": "2021-03-27T22:13:58.673333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T22:14:53.953333",
              "refreshedTime": "2021-03-27T22:14:53.953333"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-30T12:16:17.7"
              }
            ]
          },
          {
            "name": "Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ordinal",
            "lineageTag": "1ed912c0-c74c-431f-98bd-bd96c3892d08",
            "summarizeBy": "sum",
            "modifiedTime": "2021-03-30T12:16:17.7",
            "structureModifiedTime": "2021-03-27T22:13:58.673333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-03-27T22:14:53.953333",
              "refreshedTime": "2021-03-27T22:14:53.953333"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-03-30T12:16:17.7"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "state": "ready",
            "modifiedTime": "2021-03-27T22:14:53.953333",
            "refreshedTime": "2021-03-27T22:14:53.953333",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "Covid",
        "lineageTag": "2f174a8d-f7f4-4d30-a0f3-5bab866395a1",
        "modifiedTime": "2021-04-06T21:45:20.61",
        "structureModifiedTime": "2023-03-28T13:46:53.803333",
        "columns": [
          {
            "type": "rowNumber",
            "name": "RowNumber-2662979B-1795-4F74-8F37-6A1BA8059B61",
            "dataType": "int64",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "isNullable": false,
            "modifiedTime": "2021-04-06T18:08:02.853333",
            "structureModifiedTime": "2021-04-06T18:08:02.853333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-06T18:08:03.65",
              "refreshedTime": "2021-04-20T15:58:07.85"
            }
          },
          {
            "name": "Data",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Data",
            "formatString": "Long Date",
            "lineageTag": "0c5c7d68-fe9c-4578-810d-4c5d1c2a2718",
            "summarizeBy": "none",
            "modifiedTime": "2022-04-04T14:30:13.833333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-06T18:08:03.65",
              "refreshedTime": "2021-04-20T15:58:07.846667"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-04-06T18:08:02.853333"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date",
                "modifiedTime": "2021-04-06T18:08:02.853333"
              }
            ]
          },
          {
            "name": "CodiceRegioneIstat",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CodiceRegioneIstat",
            "formatString": "0",
            "lineageTag": "10c489d7-49ac-456c-a87a-8a4a42811485",
            "summarizeBy": "none",
            "modifiedTime": "2021-04-06T18:09:55.3",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-06T18:08:03.65",
              "refreshedTime": "2021-04-20T15:58:07.85"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2021-04-06T18:09:55.3"
              }
            ]
          },
          {
            "name": "Ricoverati con Sintomi",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ricoverati con Sintomi",
            "formatString": "0",
            "lineageTag": "11dd47cb-aa36-4676-96b2-aa936e07b1b4",
            "summarizeBy": "none",
            "modifiedTime": "2021-04-06T18:09:55.3",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-06T18:08:03.65",
              "refreshedTime": "2021-04-20T15:58:07.846667"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2021-04-06T18:09:55.3"
              }
            ]
          },
          {
            "name": "Terapia Intensiva",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Terapia Intensiva",
            "formatString": "0",
            "lineageTag": "b8eabe0b-5bba-40d0-8fd8-15d5964cd223",
            "summarizeBy": "none",
            "modifiedTime": "2021-04-06T18:09:55.3",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-06T18:08:03.65",
              "refreshedTime": "2021-04-20T15:58:07.843333"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2021-04-06T18:09:55.3"
              }
            ]
          },
          {
            "name": "Totale Ospedalizzati",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Totale Ospedalizzati",
            "formatString": "0",
            "lineageTag": "68f6a781-16d0-47e4-90b9-5b249c26e578",
            "summarizeBy": "none",
            "modifiedTime": "2021-04-06T18:09:55.3",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-06T18:08:03.65",
              "refreshedTime": "2021-04-20T15:58:07.866667"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2021-04-06T18:09:55.3"
              }
            ]
          },
          {
            "name": "Isolamento Domiciliare",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Isolamento Domiciliare",
            "formatString": "0",
            "lineageTag": "855e51f0-044d-4c3e-8b23-087db44ada85",
            "summarizeBy": "none",
            "modifiedTime": "2021-04-06T18:09:55.3",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-06T18:08:03.65",
              "refreshedTime": "2021-04-20T15:58:07.85"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2021-04-06T18:09:55.3"
              }
            ]
          },
          {
            "name": "Totale Positivi",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Totale Positivi",
            "formatString": "0",
            "lineageTag": "53d74a89-bda0-478f-8a2b-b3014eefe884",
            "summarizeBy": "none",
            "modifiedTime": "2021-04-06T18:09:55.3",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-06T18:08:03.65",
              "refreshedTime": "2021-04-20T15:58:07.846667"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2021-04-06T18:09:55.3"
              }
            ]
          },
          {
            "name": "Variazione Totale Positivi",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Variazione Totale Positivi",
            "formatString": "0",
            "lineageTag": "5ff3ee37-5b72-44e7-b352-70eaa736e7a0",
            "summarizeBy": "none",
            "modifiedTime": "2021-04-06T18:09:55.3",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-06T18:08:03.65",
              "refreshedTime": "2021-04-20T15:58:07.846667"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2021-04-06T18:09:55.3"
              }
            ]
          },
          {
            "name": "Nuovi Positivi",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Nuovi Positivi",
            "formatString": "0",
            "lineageTag": "5cf50736-73b1-42a9-b630-f74039b946cf",
            "summarizeBy": "none",
            "modifiedTime": "2021-04-06T18:09:55.3",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-06T18:08:03.65",
              "refreshedTime": "2021-04-20T15:58:07.85"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2021-04-06T18:09:55.3"
              }
            ]
          },
          {
            "name": "Dimessi Guariti",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Dimessi Guariti",
            "formatString": "0",
            "lineageTag": "d0b45f1c-b837-4da2-85e4-b3a5e1aa0225",
            "summarizeBy": "none",
            "modifiedTime": "2021-04-06T18:09:55.3",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-06T18:08:03.65",
              "refreshedTime": "2021-04-20T15:58:07.846667"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2021-04-06T18:09:55.3"
              }
            ]
          },
          {
            "name": "Deceduti",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Deceduti",
            "formatString": "0",
            "lineageTag": "c2d1dd18-e5cf-4e25-866a-878c0dddc302",
            "summarizeBy": "none",
            "modifiedTime": "2021-04-06T18:09:55.3",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-06T18:08:03.65",
              "refreshedTime": "2021-04-20T15:58:07.85"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2021-04-06T18:09:55.3"
              }
            ]
          },
          {
            "name": "Casi da Sospetto Diagnostico",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Casi da Sospetto Diagnostico",
            "formatString": "0",
            "lineageTag": "eec071a2-c61f-4fd0-ada5-289e2f6715fa",
            "summarizeBy": "none",
            "modifiedTime": "2021-04-06T18:09:55.3",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-06T18:08:03.65",
              "refreshedTime": "2021-04-20T15:58:07.85"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2021-04-06T18:09:55.3"
              }
            ]
          },
          {
            "name": "Casi da Screening",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Casi da Screening",
            "formatString": "0",
            "lineageTag": "a3f2e814-1259-4ea5-88ac-abe9c0ed0897",
            "summarizeBy": "none",
            "modifiedTime": "2021-04-06T18:09:55.3",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-06T18:08:03.65",
              "refreshedTime": "2021-04-20T15:58:07.85"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2021-04-06T18:09:55.3"
              }
            ]
          },
          {
            "name": "Totale Casi",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Totale Casi",
            "formatString": "0",
            "lineageTag": "7e778a51-5377-496c-9fdf-82a235d3369e",
            "summarizeBy": "none",
            "modifiedTime": "2021-04-06T18:09:55.3",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-06T18:08:03.65",
              "refreshedTime": "2021-04-20T15:58:07.846667"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2021-04-06T18:09:55.3"
              }
            ]
          },
          {
            "name": "Tamponi",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Tamponi",
            "formatString": "0",
            "lineageTag": "a8691ef0-9de9-44b3-8329-5321e2048cf6",
            "summarizeBy": "none",
            "modifiedTime": "2021-04-06T18:09:55.3",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-06T18:08:03.65",
              "refreshedTime": "2021-04-20T15:58:07.85"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2021-04-06T18:09:55.3"
              }
            ]
          },
          {
            "name": "Casi Testati",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Casi Testati",
            "formatString": "0",
            "lineageTag": "4123e7ed-8cb0-4499-b50b-172724981c6a",
            "summarizeBy": "none",
            "modifiedTime": "2021-04-06T18:09:55.3",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-06T18:08:03.65",
              "refreshedTime": "2021-04-20T15:58:07.866667"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2021-04-06T18:09:55.3"
              }
            ]
          },
          {
            "name": "Note",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Note",
            "lineageTag": "d2f14b79-52e5-422d-9b3b-af2244b88ec5",
            "summarizeBy": "none",
            "modifiedTime": "2021-04-06T18:09:03.02",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-06T18:08:03.653333",
              "refreshedTime": "2021-04-20T15:58:07.853333"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-04-06T18:08:02.853333"
              }
            ]
          },
          {
            "name": "Ingressi Terapia Intensiva",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ingressi Terapia Intensiva",
            "formatString": "0",
            "lineageTag": "e2942fc9-e539-4e68-b451-ca693037c78c",
            "summarizeBy": "none",
            "modifiedTime": "2021-04-06T18:09:55.3",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-06T18:08:03.65",
              "refreshedTime": "2021-04-20T15:58:07.843333"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2021-04-06T18:09:55.3"
              }
            ]
          },
          {
            "name": "Note Test",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Note Test",
            "lineageTag": "76615d00-acac-4997-ba10-eb2662918e24",
            "summarizeBy": "none",
            "modifiedTime": "2021-04-06T18:09:03.02",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-06T18:08:03.65",
              "refreshedTime": "2021-04-20T15:58:07.846667"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-04-06T18:08:02.853333"
              }
            ]
          },
          {
            "name": "Note Casi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Note Casi",
            "lineageTag": "d36e8808-a740-4751-ab64-949c29a9af2a",
            "summarizeBy": "none",
            "modifiedTime": "2021-04-06T18:09:03.02",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-06T18:08:03.65",
              "refreshedTime": "2021-04-20T15:58:07.866667"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-04-06T18:08:02.853333"
              }
            ]
          },
          {
            "name": "Totale Positivi Test Molecolare",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Totale Positivi Test Molecolare",
            "formatString": "0",
            "lineageTag": "39ac13bb-04f4-4e9e-971e-836cf1db3434",
            "summarizeBy": "none",
            "modifiedTime": "2021-04-06T18:09:55.3",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-06T18:08:03.65",
              "refreshedTime": "2021-04-20T15:58:07.85"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2021-04-06T18:09:55.3"
              }
            ]
          },
          {
            "name": "Totale Positivi Test Antigenico Rapido",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Totale Positivi Test Antigenico Rapido",
            "formatString": "0",
            "lineageTag": "0adc90b9-9154-4ef1-b12e-e56377bfb91a",
            "summarizeBy": "none",
            "modifiedTime": "2021-04-06T18:09:55.3",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-06T18:08:03.65",
              "refreshedTime": "2021-04-20T15:58:07.846667"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2021-04-06T18:09:55.3"
              }
            ]
          },
          {
            "name": "Tamponi Test Molecolare",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Tamponi Test Molecolare",
            "formatString": "0",
            "lineageTag": "868f3946-e6b3-469c-9b3f-02efaa46e7bf",
            "summarizeBy": "none",
            "modifiedTime": "2021-04-06T18:09:55.3",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-06T18:08:03.65",
              "refreshedTime": "2021-04-20T15:58:07.846667"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2021-04-06T18:09:55.3"
              }
            ]
          },
          {
            "name": "Tamponi Test Antigenico Rapido",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Tamponi Test Antigenico Rapido",
            "formatString": "0",
            "lineageTag": "2e8ac439-20a0-4060-80b8-a9282fb7b163",
            "summarizeBy": "none",
            "modifiedTime": "2021-04-06T18:09:55.3",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-06T18:08:03.65",
              "refreshedTime": "2021-04-20T15:58:07.846667"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2021-04-06T18:09:55.3"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Deceduti Giorno",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "Covid[Deceduti] - LOOKUPVALUE ( Covid[Deceduti], Covid[Data], Covid[Data] - 1, Covid[CodiceRegioneIstat], Covid[CodiceRegioneIstat] )",
            "formatString": "0",
            "lineageTag": "1d17b0b2-6269-40d8-89fb-d4c786432197",
            "summarizeBy": "sum",
            "modifiedTime": "2021-04-06T22:17:20.876667",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "refreshedTime": "2021-04-20T15:58:07.863333",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2021-04-06T22:17:20.876667",
              "refreshedTime": "2021-04-20T15:58:07.863333"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2021-04-06T22:12:05.923333"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Covid-f5d23989-5835-48c1-b6a4-25d9fb0151b1",
            "mode": "import",
            "state": "ready",
            "modifiedTime": "2021-04-20T11:01:05.566667",
            "refreshedTime": "2021-04-20T15:58:07.836667",
            "source": {
              "type": "m",
              "expression": "let\n    Source = #\"dpc-covid19-ita-regioni\",\n    #\"Renamed Columns\" = Table.RenameColumns(Source,{{\"data\", \"Data\"}}),\n    #\"Removed Columns\" = Table.RemoveColumns(#\"Renamed Columns\",{\"stato\"}),\n    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns\",{{\"codice_regione\", \"CodiceRegioneIstat\"}}),\n    #\"Removed Columns1\" = Table.RemoveColumns(#\"Renamed Columns1\",{\"denominazione_regione\"}),\n    #\"Renamed Columns2\" = Table.RenameColumns(#\"Removed Columns1\",{{\"ricoverati_con_sintomi\", \"Ricoverati con Sintomi\"}, {\"terapia_intensiva\", \"Terapia Intensiva\"}, {\"totale_ospedalizzati\", \"Totale Ospedalizzati\"}, {\"isolamento_domiciliare\", \"Isolamento Domiciliare\"}, {\"totale_positivi\", \"Totale Positivi\"}, {\"variazione_totale_positivi\", \"Variazione Totale Positivi\"}, {\"nuovi_positivi\", \"Nuovi Positivi\"}, {\"dimessi_guariti\", \"Dimessi Guariti\"}, {\"deceduti\", \"Deceduti\"}, {\"casi_da_sospetto_diagnostico\", \"Casi da Sospetto Diagnostico\"}, {\"casi_da_screening\", \"Casi da Screening\"}, {\"totale_casi\", \"Totale Casi\"}, {\"tamponi\", \"Tamponi\"}, {\"casi_testati\", \"Casi Testati\"}, {\"ingressi_terapia_intensiva\", \"Ingressi Terapia Intensiva\"}, {\"totale_positivi_test_molecolare\", \"Totale Positivi Test Molecolare\"}, {\"totale_positivi_test_antigenico_rapido\", \"Totale Positivi Test Antigenico Rapido\"}, {\"tamponi_test_molecolare\", \"Tamponi Test Molecolare\"}, {\"tamponi_test_antigenico_rapido\", \"Tamponi Test Antigenico Rapido\"}}),\n    #\"Removed Columns2\" = Table.RemoveColumns(#\"Renamed Columns2\",{\"codice_nuts_1\", \"codice_nuts_2\"}),\n    #\"Renamed Columns3\" = Table.RenameColumns(#\"Removed Columns2\",{{\"note\", \"Note\"}, {\"note_test\", \"Note Test\"}, {\"note_casi\", \"Note Casi\"}})\nin\n    #\"Renamed Columns3\""
            }
          }
        ],
        "measures": [
          {
            "name": "# Casi da Screening",
            "expression": "\nIF (\n    NOT ISFILTERED ( 'Età' ) && NOT ISFILTERED ( Categoria ) && NOT ISFILTERED ( Genere ),\n    VAR LastAvailableDate = MIN ( MAX ( Covid[Data] ), MAX ( Data[Data] ) )\n    VAR Result = \n        CALCULATE (\n            SUM ( Covid[Casi da Screening] ),\n            'Data'[Data] = LastAvailableDate\n        )\n    RETURN Result\n)",
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Casi",
            "lineageTag": "45efcd53-9f90-4f28-b407-c4f967da4099",
            "dataType": "int64",
            "modifiedTime": "2021-04-06T21:55:23.506667",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "DisplayFolder"
              },
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "# Casi da Sospetto Diagnostico",
            "expression": "\nIF (\n    NOT ISFILTERED ( 'Età' ) && NOT ISFILTERED ( Categoria ) && NOT ISFILTERED ( Genere ),\n    VAR LastAvailableDate = MIN ( MAX ( Covid[Data] ), MAX ( Data[Data] ) )\n    VAR Result = \n        CALCULATE (\n            SUM ( Covid[Casi da Sospetto Diagnostico] ),\n            'Data'[Data] = LastAvailableDate\n        )\n    RETURN Result\n)",
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Casi",
            "lineageTag": "b9fb3da0-e448-4469-9c85-639671504372",
            "dataType": "int64",
            "modifiedTime": "2021-04-06T21:55:27.556667",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "DisplayFolder"
              },
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "# Casi Testati",
            "expression": "\nIF (\n    NOT ISFILTERED ( 'Età' ) && NOT ISFILTERED ( Categoria ) && NOT ISFILTERED ( Genere ),\n    VAR LastAvailableDate = MIN ( MAX ( Covid[Data] ), MAX ( Data[Data] ) )\n    VAR Result = \n        CALCULATE (\n            SUM ( Covid[Casi Testati] ),\n            'Data'[Data] = LastAvailableDate\n        )\n    RETURN Result\n)",
            "formatString": "#,0",
            "displayFolder": "Casi Cumulati",
            "lineageTag": "fe2acbe9-1bfa-4453-8327-fef0d495fa79",
            "dataType": "int64",
            "modifiedTime": "2021-04-06T21:56:21.706667",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "DisplayFolder"
              }
            ]
          },
          {
            "name": "# Deceduti Cumulati",
            "expression": "\nIF (\n    NOT ISFILTERED ( 'Età' ) && NOT ISFILTERED ( Categoria ) && NOT ISFILTERED ( Genere ),\n    VAR LastAvailableDate = MIN ( MAX ( Covid[Data] ), MAX ( Data[Data] ) )\n    VAR Result = \n        CALCULATE (\n            SUM ( Covid[Deceduti] ),\n            'Data'[Data] = LastAvailableDate\n        )\n    RETURN Result\n)",
            "formatString": "#,0",
            "displayFolder": "Casi Cumulati",
            "lineageTag": "318a3658-cc13-479d-8a5f-6dd999464f35",
            "dataType": "int64",
            "modifiedTime": "2021-04-06T22:13:52.773333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "DisplayFolder"
              }
            ]
          },
          {
            "name": "# Dimessi Guariti",
            "expression": "\nIF (\n    NOT ISFILTERED ( 'Età' ) && NOT ISFILTERED ( Categoria ) && NOT ISFILTERED ( Genere ),\n    VAR LastAvailableDate = MIN ( MAX ( Covid[Data] ), MAX ( Data[Data] ) )\n    VAR Result = \n        CALCULATE (\n            SUM ( 'Covid'[Dimessi Guariti] ),\n            'Data'[Data] = LastAvailableDate\n        )\n    RETURN Result\n)",
            "formatString": "#,0",
            "displayFolder": "Casi Cumulati",
            "lineageTag": "b9df84df-41d7-4882-a8a2-dc54ca4770e7",
            "dataType": "int64",
            "modifiedTime": "2021-04-06T21:56:21.706667",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "DisplayFolder"
              }
            ]
          },
          {
            "name": "# Ingressi Terapia Intensiva",
            "expression": "\nIF (\n    NOT ISFILTERED ( 'Età' ) && NOT ISFILTERED ( Categoria ) && NOT ISFILTERED ( Genere ),\n    VAR LastAvailableDate = MIN ( MAX ( Covid[Data] ), MAX ( Data[Data] ) )\n    VAR Result = \n        CALCULATE (\n            SUM ( Covid[Ingressi Terapia Intensiva] ),\n            'Data'[Data] = LastAvailableDate\n        )\n    RETURN Result\n)",
            "formatString": "#,0",
            "displayFolder": "Ricoveri",
            "lineageTag": "296f226f-01e6-429c-bfb9-71e658036499",
            "dataType": "int64",
            "modifiedTime": "2021-04-06T21:50:02.506667",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "DisplayFolder"
              }
            ]
          },
          {
            "name": "# Isolamento Domiciliare",
            "expression": "\nIF (\n    NOT ISFILTERED ( 'Età' ) && NOT ISFILTERED ( Categoria ) && NOT ISFILTERED ( Genere ),\n    VAR LastAvailableDate = MIN ( MAX ( Covid[Data] ), MAX ( Data[Data] ) )\n    VAR Result = \n        CALCULATE (\n            SUM ( Covid[Isolamento Domiciliare] ),\n            'Data'[Data] = LastAvailableDate\n        )\n    RETURN Result\n)",
            "formatString": "#,0",
            "displayFolder": "Casi Cumulati",
            "lineageTag": "46b51369-10ac-4474-a0e3-d711ef30b0d1",
            "dataType": "int64",
            "modifiedTime": "2021-04-06T21:56:21.706667",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "DisplayFolder"
              }
            ]
          },
          {
            "name": "# Nuovi Positivi",
            "expression": "\nIF (\n    NOT ISFILTERED ( 'Età' ) && NOT ISFILTERED ( Categoria ) && NOT ISFILTERED ( Genere ),\n    VAR LastAvailableDate = MIN ( MAX ( Covid[Data] ), MAX ( Data[Data] ) )\n    VAR Result = \n        CALCULATE (\n            SUM ( 'Covid'[Nuovi Positivi] ),\n            'Data'[Data] = LastAvailableDate\n        )\n    RETURN Result\n)",
            "formatString": "#,0",
            "displayFolder": "Positivi",
            "lineageTag": "5e5237e3-882c-4b38-ad50-952fbadf52be",
            "dataType": "int64",
            "modifiedTime": "2021-04-06T21:47:38.613333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "DisplayFolder"
              }
            ]
          },
          {
            "name": "# Ricoverati con Sintomi",
            "expression": "\nIF (\n    NOT ISFILTERED ( 'Età' ) && NOT ISFILTERED ( Categoria ) && NOT ISFILTERED ( Genere ),\n    VAR LastAvailableDate = MIN ( MAX ( Covid[Data] ), MAX ( Data[Data] ) )\n    VAR Result = \n        CALCULATE (\n            SUM ( Covid[Ricoverati con Sintomi] ),\n            'Data'[Data] = LastAvailableDate\n        )\n    RETURN Result\n)",
            "formatString": "#,0",
            "displayFolder": "Ricoveri",
            "lineageTag": "e7db4657-1cc9-4bad-b9ee-6faf5f72efaa",
            "dataType": "int64",
            "modifiedTime": "2021-04-06T21:50:02.506667",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "DisplayFolder"
              }
            ]
          },
          {
            "name": "# Tamponi",
            "expression": "\nIF (\n    NOT ISFILTERED ( 'Età' ) && NOT ISFILTERED ( Categoria ) && NOT ISFILTERED ( Genere ),\n    VAR LastAvailableDate = MIN ( MAX ( Covid[Data] ), MAX ( Data[Data] ) )\n    VAR Result = \n        CALCULATE (\n            SUM ( Covid[Tamponi] ),\n            'Data'[Data] = LastAvailableDate\n        )\n    RETURN Result\n)",
            "formatString": "#,0",
            "displayFolder": "Tamponi Cumulati",
            "lineageTag": "9bf94eef-d75b-4f73-a6e1-6b188ad05e08",
            "dataType": "int64",
            "modifiedTime": "2021-04-06T22:00:30.21",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "DisplayFolder"
              }
            ]
          },
          {
            "name": "# Tamponi Test Antigenico Rapido",
            "expression": "\nIF (\n    NOT ISFILTERED ( 'Età' ) && NOT ISFILTERED ( Categoria ) && NOT ISFILTERED ( Genere ),\n    VAR LastAvailableDate = MIN ( MAX ( Covid[Data] ), MAX ( Data[Data] ) )\n    VAR Result = \n        CALCULATE (\n            SUM ( 'Covid'[Tamponi Test Antigenico Rapido] ),\n            'Data'[Data] = LastAvailableDate\n        )\n    RETURN Result\n)",
            "formatString": "#,0",
            "displayFolder": "Tamponi Cumulati",
            "lineageTag": "8da6cadf-07a9-413a-b200-bf22d999b16f",
            "dataType": "int64",
            "modifiedTime": "2021-04-06T22:00:30.21",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "DisplayFolder"
              }
            ]
          },
          {
            "name": "# Tamponi Test Molecolare",
            "expression": "\nIF (\n    NOT ISFILTERED ( 'Età' ) && NOT ISFILTERED ( Categoria ) && NOT ISFILTERED ( Genere ),\n    VAR LastAvailableDate = MIN ( MAX ( Covid[Data] ), MAX ( Data[Data] ) )\n    VAR Result = \n        CALCULATE (\n            SUM ( 'Covid'[Tamponi Test Molecolare] ),\n            'Data'[Data] = LastAvailableDate\n        )\n    RETURN Result\n)",
            "formatString": "#,0",
            "displayFolder": "Tamponi Cumulati",
            "lineageTag": "00f84d07-0cf5-4a26-bf26-47fdada344b2",
            "dataType": "int64",
            "modifiedTime": "2021-04-06T22:00:30.21",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "DisplayFolder"
              }
            ]
          },
          {
            "name": "# Terapia Intensiva",
            "expression": "\nIF (\n    NOT ISFILTERED ( 'Età' ) && NOT ISFILTERED ( Categoria ) && NOT ISFILTERED ( Genere ),\n    VAR LastAvailableDate = MIN ( MAX ( Covid[Data] ), MAX ( Data[Data] ) )\n    VAR Result = \n        CALCULATE (\n            SUM ( Covid[Terapia Intensiva] ),\n            'Data'[Data] = LastAvailableDate\n        )\n    RETURN Result\n)",
            "formatString": "#,0",
            "displayFolder": "Ricoveri",
            "lineageTag": "16178b34-8510-48f4-bf07-0e09392964ca",
            "dataType": "int64",
            "modifiedTime": "2021-04-06T21:50:02.506667",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "DisplayFolder"
              }
            ]
          },
          {
            "name": "# Totale Casi",
            "expression": "\n IF (\n    NOT ISFILTERED ( 'Età' ) && NOT ISFILTERED ( Categoria ) && NOT ISFILTERED ( Genere ),\n    VAR LastAvailableDate = MIN ( MAX ( Covid[Data] ), MAX ( Data[Data] ) )\n    VAR Result = \n        CALCULATE (\n            SUM ( Covid[Totale Casi] ),\n            'Data'[Data] = LastAvailableDate\n        )\n    RETURN Result\n)",
            "formatString": "#,0",
            "displayFolder": "Casi Cumulati",
            "lineageTag": "9b12c07c-1bb6-4334-b2ed-16999956b262",
            "dataType": "int64",
            "modifiedTime": "2021-04-06T21:56:21.706667",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "DisplayFolder"
              }
            ]
          },
          {
            "name": "# Totale Ospedalizzati",
            "expression": "\nIF (\n    NOT ISFILTERED ( 'Età' ) && NOT ISFILTERED ( Categoria ) && NOT ISFILTERED ( Genere ),\n    VAR LastAvailableDate = MIN ( MAX ( Covid[Data] ), MAX ( Data[Data] ) )\n    VAR Result = \n        CALCULATE (\n            SUM ( Covid[Totale Ospedalizzati] ),\n            'Data'[Data] = LastAvailableDate\n        )\n    RETURN Result\n)",
            "formatString": "#,0",
            "displayFolder": "Casi Cumulati",
            "lineageTag": "d7b81ea5-1d07-47db-a3be-fbd4d2f08b93",
            "dataType": "int64",
            "modifiedTime": "2021-04-06T21:56:21.706667",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "DisplayFolder"
              }
            ]
          },
          {
            "name": "# Totale Positivi",
            "expression": "\nIF (\n    NOT ISFILTERED ( 'Età' ) && NOT ISFILTERED ( Categoria ) && NOT ISFILTERED ( Genere ),\n    VAR LastAvailableDate = MIN ( MAX ( Covid[Data] ), MAX ( Data[Data] ) )\n    VAR Result = \n        CALCULATE (\n            SUM ( Covid[Totale Positivi] ),\n            'Data'[Data] = LastAvailableDate\n        )\n    RETURN Result\n)",
            "formatString": "#,0",
            "displayFolder": "Positivi",
            "lineageTag": "c1f13b1d-7a89-47bf-a45e-76643b44c52a",
            "dataType": "int64",
            "modifiedTime": "2021-04-06T21:47:22.473333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "DisplayFolder"
              }
            ]
          },
          {
            "name": "# Totale Positivi Test Antigenico Rapido",
            "expression": "\nIF (\n    NOT ISFILTERED ( 'Età' ) && NOT ISFILTERED ( Categoria ) && NOT ISFILTERED ( Genere ),\n    VAR LastAvailableDate = MIN ( MAX ( Covid[Data] ), MAX ( Data[Data] ) )\n    VAR Result = \n        CALCULATE (\n            SUM ( Covid[Totale Positivi Test Antigenico Rapido] ),\n            'Data'[Data] = LastAvailableDate\n        )\n    RETURN Result\n)",
            "formatString": "#,0",
            "displayFolder": "Tamponi Cumulati",
            "lineageTag": "9a6a9e0f-03ba-4a08-ab1d-32ca17934f1f",
            "dataType": "int64",
            "modifiedTime": "2021-04-06T22:00:36.85",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "DisplayFolder"
              }
            ]
          },
          {
            "name": "# Totale Positivi Test Molecolare",
            "expression": "\nIF (\n    NOT ISFILTERED ( 'Età' ) && NOT ISFILTERED ( Categoria ) && NOT ISFILTERED ( Genere ),\n    VAR LastAvailableDate = MIN ( MAX ( Covid[Data] ), MAX ( Data[Data] ) )\n    VAR Result = \n        CALCULATE (\n            SUM ( Covid[Totale Positivi Test Molecolare] ),\n            'Data'[Data] = LastAvailableDate\n        )\n    RETURN Result\n)\n",
            "formatString": "#,0",
            "displayFolder": "Tamponi Cumulati",
            "lineageTag": "aa7e4812-9128-4935-bb1b-d5459d74034b",
            "dataType": "int64",
            "modifiedTime": "2021-04-06T22:00:36.85",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "DisplayFolder"
              }
            ]
          },
          {
            "name": "# Variazione Totale Positivi",
            "expression": "\nIF (\n    NOT ISFILTERED ( 'Età' ) && NOT ISFILTERED ( Categoria ) && NOT ISFILTERED ( Genere ),\n    VAR LastAvailableDate = MIN ( MAX ( Covid[Data] ), MAX ( Data[Data] ) )\n    VAR Result = \n        CALCULATE (\n            SUM ( Covid[Variazione Totale Positivi] ),\n            'Data'[Data] = LastAvailableDate\n        )\n    RETURN Result\n)",
            "formatString": "#,0",
            "displayFolder": "Positivi",
            "lineageTag": "e7fe6755-40c3-4fa1-9059-c9d23f97aeb8",
            "dataType": "int64",
            "modifiedTime": "2021-04-06T21:47:28.343333",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "DisplayFolder"
              }
            ]
          },
          {
            "name": "% Deceduti",
            "expression": "DIVIDE ( [# Deceduti Cumulati], [# Totale Casi] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Casi Cumulati",
            "lineageTag": "9568af6f-119f-4531-9d05-34a30df466cf",
            "dataType": "double",
            "modifiedTime": "2021-04-12T14:21:16.016667",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "DisplayFolder"
              }
            ]
          },
          {
            "name": "# Deceduti",
            "expression": "\nIF (\n    NOT ISFILTERED ( 'Età' ) && NOT ISFILTERED ( Categoria ) && NOT ISFILTERED ( Genere ),\n    VAR LastAvailableDate = MIN ( MAX ( Covid[Data] ), MAX ( Data[Data] ) )\n    VAR Result = \n        CALCULATE (\n            SUM ( Covid[Deceduti Giorno] ),\n            'Data'[Data] = LastAvailableDate\n        )\n    RETURN Result\n)",
            "formatString": "#,0",
            "displayFolder": "Ricoveri",
            "lineageTag": "3052ca36-8d35-47e0-a779-78ae60082b2f",
            "dataType": "int64",
            "modifiedTime": "2021-04-06T22:16:34.966667",
            "structureModifiedTime": "2023-03-28T13:46:53.803333",
            "changedProperties": [
              {
                "property": "DisplayFolder"
              },
              {
                "property": "FormatString"
              }
            ]
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table",
            "modifiedTime": "2021-04-06T18:08:02.853333"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "7d4525ab-6439-409b-86d6-0423acafc50a",
        "fromTable": "SomministrazioniGenere",
        "fromColumn": "CodiceGenere",
        "toTable": "Genere",
        "toColumn": "CodiceGenere",
        "state": "ready",
        "modifiedTime": "2021-04-20T07:47:23.373333",
        "refreshedTime": "2021-04-20T15:58:07.473333"
      },
      {
        "name": "5706ea73-b236-4e9c-92f0-22e41e620eb3",
        "fromTable": "SomministrazioniCategoria",
        "fromColumn": "FasciaAnagrafica",
        "toTable": "Età",
        "toColumn": "FasciaAnagrafica",
        "state": "ready",
        "modifiedTime": "2021-04-20T07:47:23.833333",
        "refreshedTime": "2021-04-20T15:58:07.763333"
      },
      {
        "name": "b431da1a-8d9f-4acd-b97b-7b1795b65835",
        "fromTable": "Somministrazioni",
        "fromColumn": "FasciaAnagrafica",
        "toTable": "Età",
        "toColumn": "FasciaAnagrafica",
        "state": "ready",
        "modifiedTime": "2021-03-27T18:04:01.423333",
        "refreshedTime": "2021-04-20T15:58:07.65"
      },
      {
        "name": "592536b5-b7b0-4925-932a-5564a59ccd6b",
        "fromTable": "SomministrazioniGenere",
        "fromColumn": "FasciaAnagrafica",
        "toTable": "Età",
        "toColumn": "FasciaAnagrafica",
        "state": "ready",
        "modifiedTime": "2021-04-20T07:47:23.373333",
        "refreshedTime": "2021-04-20T15:58:07.673333"
      },
      {
        "name": "4fa2626c-15bf-458b-95d2-9faeabe7abe5",
        "fromTable": "SomministrazioniCategoria",
        "fromColumn": "CodiceCategoria",
        "toTable": "Categoria",
        "toColumn": "CodiceCategoria",
        "state": "ready",
        "modifiedTime": "2021-04-20T07:47:23.813333",
        "refreshedTime": "2021-04-20T15:58:07.763333"
      },
      {
        "name": "3489a06c-9f1a-4dd9-998a-a398fd851898",
        "fromTable": "Consegne",
        "fromColumn": "CodiceFornitore",
        "toTable": "Fornitore",
        "toColumn": "CodiceFornitore",
        "state": "ready",
        "modifiedTime": "2021-03-27T18:04:01.42",
        "refreshedTime": "2021-04-20T15:58:07.663333"
      },
      {
        "name": "bc9bc8af-b482-4401-8902-066622ded854",
        "fromTable": "SomministrazioniCategoria",
        "fromColumn": "CodiceFornitore",
        "toTable": "Fornitore",
        "toColumn": "CodiceFornitore",
        "state": "ready",
        "modifiedTime": "2021-04-20T07:47:23.816667",
        "refreshedTime": "2021-04-20T15:58:07.77"
      },
      {
        "name": "74afdc78-421f-428b-92c2-f84d55a3852d",
        "fromTable": "Somministrazioni",
        "fromColumn": "CodiceFornitore",
        "toTable": "Fornitore",
        "toColumn": "CodiceFornitore",
        "state": "ready",
        "modifiedTime": "2021-03-27T18:04:01.423333",
        "refreshedTime": "2021-04-20T15:58:07.66"
      },
      {
        "name": "a49c7b8a-bdc8-4a03-9b7e-e024f0c7bd27",
        "fromTable": "SomministrazioniGenere",
        "fromColumn": "CodiceFornitore",
        "toTable": "Fornitore",
        "toColumn": "CodiceFornitore",
        "state": "ready",
        "modifiedTime": "2021-04-20T07:47:23.373333",
        "refreshedTime": "2021-04-20T15:58:07.663333"
      },
      {
        "name": "a4f332fd-3d5e-4013-aa2f-cc4ebaff5cd4",
        "fromTable": "Consegne",
        "fromColumn": "CodiceArea",
        "toTable": "Area",
        "toColumn": "CodiceArea",
        "state": "ready",
        "modifiedTime": "2021-03-27T18:04:01.363333",
        "refreshedTime": "2021-04-20T15:58:06.693333"
      },
      {
        "name": "07e49e33-97e1-42ba-9194-102ed2144e05",
        "fromTable": "SomministrazioniCategoria",
        "fromColumn": "CodiceArea",
        "toTable": "Area",
        "toColumn": "CodiceArea",
        "state": "ready",
        "modifiedTime": "2021-04-20T07:47:23.816667",
        "refreshedTime": "2021-04-20T15:58:07.763333"
      },
      {
        "name": "93554dad-9258-4bff-bef1-066a83ff9073",
        "fromTable": "Somministrazioni",
        "fromColumn": "CodiceArea",
        "toTable": "Area",
        "toColumn": "CodiceArea",
        "state": "ready",
        "modifiedTime": "2021-03-27T18:04:01.423333",
        "refreshedTime": "2021-04-20T15:58:06.95"
      },
      {
        "name": "4ccf1c68-e391-4a63-a3ef-ccf194771e3e",
        "fromTable": "SomministrazioniGenere",
        "fromColumn": "CodiceArea",
        "toTable": "Area",
        "toColumn": "CodiceArea",
        "state": "ready",
        "modifiedTime": "2021-04-20T07:47:23.373333",
        "refreshedTime": "2021-04-20T15:58:07.253333"
      },
      {
        "name": "9d19d04f-3cc4-4125-9f1d-449f8d59106e",
        "fromTable": "SomministrazioniCategoria",
        "fromColumn": "Data",
        "toTable": "Data",
        "toColumn": "Data",
        "state": "ready",
        "modifiedTime": "2021-04-20T07:47:23.85",
        "refreshedTime": "2021-04-20T15:58:07.863333"
      },
      {
        "name": "d1ddc139-1c31-4130-98c1-ac0c8a5f4c82",
        "fromTable": "Somministrazioni",
        "fromColumn": "Data",
        "toTable": "Data",
        "toColumn": "Data",
        "state": "ready",
        "modifiedTime": "2021-04-20T07:47:23.826667",
        "refreshedTime": "2021-04-20T15:58:07.863333"
      },
      {
        "name": "f4cb44e6-bc06-4e41-9833-1be4062bf583",
        "fromTable": "SomministrazioniGenere",
        "fromColumn": "Data",
        "toTable": "Data",
        "toColumn": "Data",
        "state": "ready",
        "modifiedTime": "2021-04-20T07:47:23.85",
        "refreshedTime": "2021-04-20T15:58:07.866667"
      },
      {
        "name": "798d56a9-b47d-4196-9c01-588ffefc1dc7",
        "fromTable": "Consegne",
        "fromColumn": "Data",
        "toTable": "Data",
        "toColumn": "Data",
        "state": "ready",
        "modifiedTime": "2021-04-20T07:47:23.826667",
        "refreshedTime": "2021-04-20T15:58:07.88"
      },
      {
        "name": "c1d6e373-4031-4efc-95ef-4cc5a423c5cf",
        "fromTable": "Popolazione 2020",
        "fromColumn": "CodiceGenere",
        "toTable": "Genere",
        "toColumn": "CodiceGenere",
        "state": "ready",
        "modifiedTime": "2021-03-27T20:37:52.743333",
        "refreshedTime": "2021-04-20T15:58:07.473333"
      },
      {
        "name": "70c4bb5d-9b60-4faa-953f-7ad8e445bc16",
        "fromTable": "Popolazione 2020",
        "fromColumn": "FasciaAnagrafica",
        "toTable": "Età",
        "toColumn": "FasciaAnagrafica",
        "state": "ready",
        "modifiedTime": "2021-03-27T20:43:41.56",
        "refreshedTime": "2021-04-20T15:58:07.666667"
      },
      {
        "name": "8ed2d0de-9c11-4cf0-89c3-a009abd885de",
        "fromTable": "Popolazione 2020",
        "fromColumn": "NUTS2",
        "toTable": "Area",
        "toColumn": "NUTS2",
        "state": "ready",
        "modifiedTime": "2021-03-27T22:01:09.846667",
        "refreshedTime": "2021-04-20T15:58:06.7"
      },
      {
        "name": "c6524e11-c343-41a0-a0b3-11fac7494dca",
        "fromTable": "Covid",
        "fromColumn": "Data",
        "toTable": "Data",
        "toColumn": "Data",
        "state": "ready",
        "modifiedTime": "2021-04-20T07:47:23.826667",
        "refreshedTime": "2021-04-20T15:58:07.87"
      },
      {
        "name": "d69391ee-c009-4e07-b58f-0634179b1ee5",
        "fromTable": "Covid",
        "fromColumn": "CodiceRegioneIstat",
        "toTable": "Area",
        "toColumn": "CodiceRegioneIstat",
        "state": "ready",
        "modifiedTime": "2021-04-06T21:23:50.836667",
        "refreshedTime": "2021-04-20T15:58:07.88"
      }
    ],
    "cultures": [
      {
        "name": "en-US",
        "modifiedTime": "2021-03-27T18:03:55.97",
        "structureModifiedTime": "2021-03-27T18:03:55.97",
        "linguisticMetadata": {}
      },
      {
        "name": "it-IT",
        "modifiedTime": "2021-03-30T12:16:17.7",
        "structureModifiedTime": "2023-03-28T13:46:53.593333",
        "linguisticMetadata": {}
      }
    ],
    "expressions": [
      {
        "name": "DosiFornitore",
        "kind": "m",
        "expression": "let\n    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WCkjLrEot0nfKzPcLSU3OUNKBigAZRkqxOtFKvvkpqUV5iUA+ggWRcSwuKUqMSs1LTQaJofIgKsISK6pSy4oyExU0kKQ1caj2SswrLk7NA/K98jPyivPzFGJKDQyMzBS89IBihkqxsQA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [CodiceFornitore = _t, Fornitore = _t, Dosi = _t]),\n    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Fornitore\", type text}, {\"Dosi\", Int64.Type}})\nin\n    #\"Changed Type\"",
        "lineageTag": "e5f41081-1da1-450f-90d4-8a107c70f732",
        "modifiedTime": "2021-04-20T11:01:05.566667",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation",
            "modifiedTime": "2021-03-27T18:03:55.973333"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table",
            "modifiedTime": "2021-03-27T18:03:55.973333"
          }
        ]
      },
      {
        "name": "SomministrazioniBase",
        "kind": "m",
        "expression": "let\n    Source = #\"somministrazioni-vaccini-latest\",\n    #\"Renamed Columns\" = Table.RenameColumns(Source,{{\"data_somministrazione\", \"Data\"}, {\"fornitore\", \"CodiceFornitore\"}, {\"area\", \"CodiceArea\"}, {\"fascia_anagrafica\", \"FasciaAnagrafica\"}})\nin\n    #\"Renamed Columns\"",
        "lineageTag": "5ba375fe-3176-4b2f-bf0d-d34c543dd4ad",
        "modifiedTime": "2021-04-20T11:01:05.566667",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation",
            "modifiedTime": "2021-03-27T18:03:55.973333"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table",
            "modifiedTime": "2021-03-27T18:03:55.973333"
          }
        ]
      },
      {
        "name": "anagrafica-vaccini-summary-latest",
        "kind": "m",
        "expression": "let\n    Source = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/italia/covid19-opendata-vaccini/master/dati/anagrafica-vaccini-summary-latest.csv\"),[Delimiter=\",\", Columns=14, Encoding=1252, QuoteStyle=QuoteStyle.None]),\n    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),\n    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"fascia_anagrafica\", type text}, {\"totale\", Int64.Type}, {\"sesso_maschile\", Int64.Type}, {\"sesso_femminile\", Int64.Type}, {\"categoria_operatori_sanitari_sociosanitari\", Int64.Type}, {\"categoria_personale_non_sanitario\", Int64.Type}, {\"categoria_altro\", Int64.Type}, {\"categoria_ospiti_rsa\", Int64.Type}, {\"categoria_over80\", Int64.Type}, {\"categoria_forze_armate\", Int64.Type}, {\"categoria_personale_scolastico\", Int64.Type}})\nin\n    #\"Changed Type\"",
        "lineageTag": "6f8c0877-a1fc-486c-8b1e-f968af822157",
        "modifiedTime": "2021-04-20T11:01:05.566667",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation",
            "modifiedTime": "2021-03-27T18:03:55.973333"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table",
            "modifiedTime": "2021-03-27T18:03:55.973333"
          }
        ]
      },
      {
        "name": "consegne-vaccini-latest",
        "kind": "m",
        "expression": "let\n    Source = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/italia/covid19-opendata-vaccini/master/dati/consegne-vaccini-latest.csv\"),[Delimiter=\",\", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),\n    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),\n    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"area\", type text}, {\"fornitore\", type text}, {\"numero_dosi\", Int64.Type}, {\"data_consegna\", type date}, {\"codice_NUTS1\", type text}, {\"codice_NUTS2\", type text}, {\"codice_regione_ISTAT\", Int64.Type}, {\"nome_area\", type text}})\nin\n    #\"Changed Type\"",
        "lineageTag": "3a88488a-c871-4e72-8126-0ae2547db395",
        "modifiedTime": "2021-04-20T11:01:05.566667",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation",
            "modifiedTime": "2021-03-27T18:03:55.973333"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table",
            "modifiedTime": "2021-03-27T18:03:55.973333"
          }
        ]
      },
      {
        "name": "punti-somministrazione-latest",
        "kind": "m",
        "expression": "let\n    Source = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/italia/covid19-opendata-vaccini/master/dati/punti-somministrazione-latest.csv\"),[Delimiter=\",\", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.Csv]),\n    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),\n    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"area\", type text}, {\"provincia\", type text}, {\"comune\", type text}, {\"presidio_ospedaliero\", type text}, {\"codice_NUTS1\", type text}, {\"codice_NUTS2\", type text}, {\"codice_regione_ISTAT\", Int64.Type}, {\"nome_area\", type text}})\nin\n    #\"Changed Type\"",
        "lineageTag": "b6c78360-f4bc-4206-946c-0d92b8e4cd46",
        "modifiedTime": "2021-04-20T11:01:05.566667",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation",
            "modifiedTime": "2021-03-27T18:03:55.973333"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table",
            "modifiedTime": "2021-03-27T18:03:55.973333"
          }
        ]
      },
      {
        "name": "punti-somministrazione-tipologia",
        "kind": "m",
        "expression": "let\n    Source = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/italia/covid19-opendata-vaccini/master/dati/punti-somministrazione-tipologia.csv\"),[Delimiter=\",\", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),\n    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),\n    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"area\", type text}, {\"denominazione_struttura\", type text}, {\"tipologia\", type text}, {\"codice_NUTS1\", type text}, {\"codice_NUTS2\", type text}, {\"codice_regione_ISTAT\", Int64.Type}, {\"nome_area\", type text}})\nin\n    #\"Changed Type\"",
        "lineageTag": "59930bd8-05e6-4803-8091-3ffec2c14dfc",
        "modifiedTime": "2021-04-20T11:01:05.566667",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation",
            "modifiedTime": "2021-03-27T18:03:55.973333"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table",
            "modifiedTime": "2021-03-27T18:03:55.973333"
          }
        ]
      },
      {
        "name": "somministrazioni-vaccini-latest",
        "kind": "m",
        "expression": "let\n    Source = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/italia/covid19-opendata-vaccini/master/dati/\\somministrazioni-vaccini-latest.csv\"),[Delimiter=\",\", Columns=19, Encoding=1252, QuoteStyle=QuoteStyle.None]),\n    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),\n    #\"Removed Columns\" = Table.RemoveColumns(#\"Promoted Headers\",{\"codice_NUTS1\"}),\n    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Columns\",{{\"data_somministrazione\", type date}, {\"fornitore\", type text}, {\"area\", type text}, {\"fascia_anagrafica\", type text}, {\"sesso_maschile\", Int64.Type}, {\"sesso_femminile\", Int64.Type}, {\"categoria_operatori_sanitari_sociosanitari\", Int64.Type}, {\"categoria_personale_non_sanitario\", Int64.Type}, {\"categoria_ospiti_rsa\", Int64.Type}, {\"categoria_over80\", Int64.Type}, {\"categoria_forze_armate\", Int64.Type}, {\"categoria_personale_scolastico\", Int64.Type}, {\"categoria_altro\", Int64.Type}, {\"prima_dose\", Int64.Type}, {\"seconda_dose\", Int64.Type}})\nin\n    #\"Changed Type\"",
        "lineageTag": "9aea3349-9eee-4632-b2b5-5eb712a1881a",
        "modifiedTime": "2021-04-20T11:01:05.566667",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation",
            "modifiedTime": "2021-03-27T18:03:55.973333"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table",
            "modifiedTime": "2021-03-27T18:03:55.973333"
          }
        ]
      },
      {
        "name": "somministrazioni-vaccini-summary-latest",
        "kind": "m",
        "expression": "let\n    Source = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/italia/covid19-opendata-vaccini/master/dati/\\somministrazioni-vaccini-summary-latest.csv\"),[Delimiter=\",\", Columns=18, Encoding=1252, QuoteStyle=QuoteStyle.None]),\n    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),\n    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"data_somministrazione\", type date}, {\"area\", type text}, {\"totale\", Int64.Type}, {\"sesso_maschile\", Int64.Type}, {\"sesso_femminile\", Int64.Type}, {\"categoria_operatori_sanitari_sociosanitari\", Int64.Type}, {\"categoria_personale_non_sanitario\", Int64.Type}, {\"categoria_altro\", Int64.Type}, {\"categoria_ospiti_rsa\", Int64.Type}, {\"categoria_over80\", Int64.Type}, {\"categoria_forze_armate\", Int64.Type}, {\"categoria_personale_scolastico\", Int64.Type}, {\"prima_dose\", Int64.Type}, {\"seconda_dose\", Int64.Type}}),\n    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"codice_NUTS1\"})\nin\n    #\"Removed Columns\"",
        "lineageTag": "c13c4b8d-8c4f-4ae8-8c13-d0dcdc259815",
        "modifiedTime": "2021-04-20T11:01:05.566667",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation",
            "modifiedTime": "2021-03-27T18:03:55.973333"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table",
            "modifiedTime": "2021-03-27T18:03:55.973333"
          }
        ]
      },
      {
        "name": "vaccini-summary-latest",
        "kind": "m",
        "expression": "let\n    Source = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/italia/covid19-opendata-vaccini/master/dati/vaccini-summary-latest.csv\"),[Delimiter=\",\", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),\n    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),\n    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"area\", type text}, {\"dosi_somministrate\", Int64.Type}, {\"dosi_consegnate\", Int64.Type}, {\"percentuale_somministrazione\", type number}, {\"ultimo_aggiornamento\", type date}, {\"codice_NUTS1\", type text}, {\"codice_NUTS2\", type text}, {\"codice_regione_ISTAT\", Int64.Type}, {\"nome_area\", type text}})\nin\n    #\"Changed Type\"",
        "lineageTag": "ba5df75a-5377-49d1-b71d-418520c9afcb",
        "modifiedTime": "2021-04-20T11:01:05.566667",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation",
            "modifiedTime": "2021-03-27T18:03:55.973333"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table",
            "modifiedTime": "2021-03-27T18:03:55.973333"
          }
        ]
      },
      {
        "name": "MacroArea",
        "kind": "m",
        "expression": "let\n    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45W8gxxVtJR8ssvSlHwL0stLgFyDJVidUASbkB2cGkKkDSBirgD2Z7F+TmpQNoUKuYB0+4K1mwEFfYEsp1T80qK8oEMY6XYWAA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [NUTS1 = _t, #\"Macro Area\" = _t, Ordine = _t]),\n    #\"Changed Type1\" = Table.TransformColumnTypes(Source,{{\"Ordine\", Int64.Type}}),\n    #\"Changed Type\" = Table.TransformColumnTypes(#\"Changed Type1\",{{\"NUTS1\", type text}, {\"Macro Area\", type text}})\nin\n    #\"Changed Type\"",
        "lineageTag": "cd697893-cd9b-40dc-b172-159789cab5cb",
        "modifiedTime": "2021-04-20T11:01:05.566667",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation",
            "modifiedTime": "2021-03-27T18:03:55.973333"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table",
            "modifiedTime": "2021-03-27T18:03:55.973333"
          }
        ]
      },
      {
        "name": "AreaDescrizione",
        "kind": "m",
        "expression": "let\n    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"TZDNqsIwEEZfpXStovVeXVextXAF0epGu5jWUAfyc0mbTZ7eTCGJy5xhvu9MHo+0qverdJaekQklR5Y2s4lljt2Bc5a8nma5zLa5Gkbw07Wb/mFvNAb0Q0iJFvQrwIKS81Yba5VHFHxSHAdfVVDYHsQ/yLhIaWfT80h+HdnBgBw7CCLFZtrl0EaTkkqv2GFcLqn06sxYLz07Tlcv8kWyU9yC9ILHzPNaMzkGTJZ3Jlkk5FhoNBznNLAISUmv0EDKB0Ee84sSELsr6q7V0EFEVHsTX3dU1HgC3b39T1XTH4NFp9B8AA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [NUTS2 = _t, Regione = _t]),\n    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"NUTS2\", type text}, {\"Regione\", type text}})\nin\n    #\"Changed Type\"",
        "lineageTag": "80fba844-832f-482b-9553-de5dbdf30b13",
        "modifiedTime": "2021-04-20T11:01:05.566667",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation",
            "modifiedTime": "2021-03-27T18:03:55.973333"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table",
            "modifiedTime": "2021-03-27T18:03:55.973333"
          }
        ]
      },
      {
        "name": "Popolazione1",
        "kind": "m",
        "expression": "let\n    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"dZzNru2oEYXf5UzTA34LGCeKlHlmrX7/14j3Wt7gnM89uLoSaxuooig+Yzh//vnz\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [NUTS2 = _t, CodiceGenere = _t, #\"Eta 2020\" = _t, Popolazione = _t]),\n    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"NUTS2\", type text}, {\"CodiceGenere\", type text}, {\"Eta 2020\", Int64.Type}, {\"Popolazione\", Int64.Type}})\nin\n    #\"Changed Type\"",
        "lineageTag": "dfb25adf-779b-4f5d-a0eb-29d417e6e035",
        "modifiedTime": "2021-04-20T11:01:05.566667",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation",
            "modifiedTime": "2021-03-27T20:37:52.066667"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table",
            "modifiedTime": "2021-03-27T20:37:52.066667"
          }
        ]
      },
      {
        "name": "Popolazione2",
        "kind": "m",
        "expression": "let\n    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"dZzJki2pEUT/pbbSgnnYS22mvXYy/f9viOueBal7eIsue5Z+GTwIAieA/s9/fv71\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [NUTS2 = _t, CodiceGenere = _t, #\"Eta 2020\" = _t, Popolazione = _t]),\n    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"NUTS2\", type text}, {\"CodiceGenere\", type text}, {\"Eta 2020\", Int64.Type}, {\"Popolazione\", Int64.Type}})\nin\n    #\"Changed Type\"",
        "lineageTag": "5973f25d-d764-4a65-8a6a-b771de3cb9f4",
        "modifiedTime": "2021-04-20T11:01:05.566667",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation",
            "modifiedTime": "2021-03-27T20:37:52.066667"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table",
            "modifiedTime": "2021-03-27T20:37:52.066667"
          }
        ]
      },
      {
        "name": "Popolazione3",
        "kind": "m",
        "expression": "let\n    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"bZtLki0pEkP3ktOuAf/PBqqs5j0rq/1vo7lSXIjOw+ClPQtlBLhwHCHIf/75+fu/\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [NUTS2 = _t, CodiceGenere = _t, #\"Eta 2020\" = _t, Popolazione = _t]),\n    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"NUTS2\", type text}, {\"CodiceGenere\", type text}, {\"Eta 2020\", Int64.Type}, {\"Popolazione\", Int64.Type}})\nin\n    #\"Changed Type\"",
        "lineageTag": "ee45c8a5-6b06-4118-91c7-4f437da2f07e",
        "modifiedTime": "2021-04-20T11:01:05.566667",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation",
            "modifiedTime": "2021-03-27T20:37:52.066667"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table",
            "modifiedTime": "2021-03-27T20:37:52.066667"
          }
        ]
      },
      {
        "name": "Popolazione4",
        "kind": "m",
        "expression": "let\n    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"dVzN0iwpCn2Xu+6FCP6tKysrZjG72XX0+7/GmJAlkqd6ceOLkNKjgApH8v7995//\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [NUTS2 = _t, CodiceGenere = _t, #\"Eta 2020\" = _t, Popolazione = _t]),\n    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"NUTS2\", type text}, {\"CodiceGenere\", type text}, {\"Eta 2020\", Int64.Type}, {\"Popolazione\", Int64.Type}})\nin\n    #\"Changed Type\"",
        "lineageTag": "b6dfea10-faa2-4d78-9dca-f32a007e741c",
        "modifiedTime": "2021-04-20T11:01:05.566667",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation",
            "modifiedTime": "2021-03-27T20:58:57.386667"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table",
            "modifiedTime": "2021-03-27T20:58:57.386667"
          }
        ]
      },
      {
        "name": "Popolazione5",
        "kind": "m",
        "expression": "let\n    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"dVy9snM7in2XG3cgkEBSfLztmmCyybr6/V9jZJDFxssd3FtfmWLzI4RgCZ1///uf\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [NUTS2 = _t, CodiceGenere = _t, #\"Eta 2020\" = _t, Popolazione = _t]),\n    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"NUTS2\", type text}, {\"CodiceGenere\", type text}, {\"Eta 2020\", Int64.Type}, {\"Popolazione\", Int64.Type}})\nin\n    #\"Changed Type\"",
        "lineageTag": "725695ca-5bd1-4d99-929a-56b29006ff48",
        "modifiedTime": "2021-04-20T11:01:05.566667",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation",
            "modifiedTime": "2021-03-27T20:58:57.386667"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table",
            "modifiedTime": "2021-03-27T20:58:57.386667"
          }
        ]
      },
      {
        "name": "Popolazione6",
        "kind": "m",
        "expression": "let\n    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"bZs7suQ2DEX3Mqkd8P+JX7e6HDhzNjX734YlQCKEPgpcfkU0eUHyCgAvOb9///rn\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [NUTS2 = _t, CodiceGenere = _t, #\"Eta 2020\" = _t, Popolazione = _t]),\n    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"NUTS2\", type text}, {\"CodiceGenere\", type text}, {\"Eta 2020\", Int64.Type}, {\"Popolazione\", Int64.Type}})\nin\n    #\"Changed Type\"",
        "lineageTag": "c9827db5-1a2c-465a-ac5c-2f56c5dbe706",
        "modifiedTime": "2021-04-20T11:01:05.566667",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation",
            "modifiedTime": "2021-03-27T20:58:57.386667"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table",
            "modifiedTime": "2021-03-27T20:58:57.386667"
          }
        ]
      },
      {
        "name": "dpc-covid19-ita-regioni",
        "kind": "m",
        "expression": "let\n    Source = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-regioni/dpc-covid19-ita-regioni.csv\"),[Delimiter=\",\", Columns=30, Encoding=65001, QuoteStyle=QuoteStyle.None]),\n    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),\n    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"data\", type datetime}}),\n    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Changed Type\",{{\"data\", type date}}),\n    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type1\",{\"lat\", \"long\"}),\n    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Removed Columns\",{{\"ricoverati_con_sintomi\", Int64.Type}, {\"terapia_intensiva\", Int64.Type}, {\"totale_ospedalizzati\", Int64.Type}, {\"isolamento_domiciliare\", Int64.Type}, {\"totale_positivi\", Int64.Type}, {\"variazione_totale_positivi\", Int64.Type}, {\"nuovi_positivi\", Int64.Type}, {\"dimessi_guariti\", Int64.Type}, {\"deceduti\", Int64.Type}, {\"casi_da_sospetto_diagnostico\", Int64.Type}, {\"casi_da_screening\", Int64.Type}, {\"totale_casi\", Int64.Type}, {\"tamponi\", Int64.Type}, {\"casi_testati\", Int64.Type}, {\"ingressi_terapia_intensiva\", Int64.Type}, {\"totale_positivi_test_molecolare\", Int64.Type}, {\"totale_positivi_test_antigenico_rapido\", Int64.Type}, {\"tamponi_test_molecolare\", Int64.Type}, {\"tamponi_test_antigenico_rapido\", Int64.Type}}),\n    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type2\", each true),\n    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Filtered Rows\",{{\"codice_regione\", Int64.Type}})\nin\n    #\"Changed Type3\"",
        "lineageTag": "e1633d77-7219-4b9b-8beb-504701471f7a",
        "modifiedTime": "2021-04-20T11:01:05.566667",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation",
            "modifiedTime": "2021-04-06T18:08:02.853333"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table",
            "modifiedTime": "2021-04-06T18:08:02.853333"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.115.842.0",
        "modifiedTime": "2023-03-28T13:46:53.593333"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0",
        "modifiedTime": "2021-03-27T18:03:55.973333"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"anagrafica-vaccini-summary-latest\",\"consegne-vaccini-latest\",\"punti-somministrazione-latest\",\"punti-somministrazione-tipologia\",\"somministrazioni-vaccini-latest\",\"somministrazioni-vaccini-summary-latest\",\"vaccini-summary-latest\",\"Genere\",\"Età\",\"Categoria\",\"Fornitore\",\"DosiFornitore\",\"Consegne\",\"SomministrazioniBase\",\"SomministrazioniCategoria\",\"Somministrazioni\",\"SomministrazioniGenere\",\"Area\",\"MacroArea\",\"AreaDescrizione\",\"Popolazione1\",\"Popolazione2\",\"Popolazione3\",\"Popolazione 2020\",\"Popolazione4\",\"Popolazione5\",\"Popolazione6\",\"Covid\",\"dpc-covid19-ita-regioni\"]",
        "modifiedTime": "2021-04-06T18:08:02.853333"
      },
      {
        "name": "TabularEditor_SerializeOptions",
        "value": "{\"IgnoreInferredObjects\":false,\"IgnoreInferredProperties\":false,\"IgnoreTimestamps\":false,\"SplitMultilineStrings\":true,\"PrefixFilenames\":false,\"LocalTranslations\":false,\"LocalPerspectives\":false,\"LocalRelationships\":false,\"Levels\":[]}",
        "modifiedTime": "2021-03-27T18:03:55.973333"
      },
      {
        "name": "__TEdtr",
        "value": "1",
        "modifiedTime": "2021-03-27T18:03:55.973333"
      }
    ]
  }
}