{
  "name": "Contoso",
  "compatibilityLevel": 1550,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Currency",
        "lineageTag": "c46555e4-46af-4b82-b444-f040555b1718",
        "columns": [
          {
            "name": "CurrencyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CurrencyKey",
            "lineageTag": "1e0d236e-fc2d-4c6e-8af8-17b6b64c861a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Currency Code",
            "dataType": "string",
            "sourceColumn": "Currency Code",
            "lineageTag": "bc7edaea-7a8d-49ad-98b7-e996424f4fbf",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Currency",
            "dataType": "string",
            "sourceColumn": "Currency",
            "lineageTag": "aa8fb60f-2360-4279-9a5c-444552fffc5e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Currency",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"Demo\", \"ContosoRetailDW\", [Query=\"SELECT [DaxBook].[Currency].* #(tab)#(tab)FROM [DaxBook].[Currency]\"]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"CurrencyKey\", \"CurrencyKey\"}, {\"Currency Code\", \"Currency Code\"}, {\"Currency\", \"Currency\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"CurrencyKey\", Int64.Type}, {\"Currency Code\", type text}, {\"Currency\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ]
      },
      {
        "name": "Customer",
        "lineageTag": "dba58ade-a778-468a-ace8-755b1ac530f5",
        "columns": [
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CustomerKey",
            "lineageTag": "28258688-e1b8-4e9c-801b-3e67758c0e73",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "GeographyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "GeographyKey",
            "lineageTag": "18faee73-fec8-484a-9573-ec21faedec3d",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Customer Code",
            "dataType": "string",
            "sourceColumn": "Customer Code",
            "lineageTag": "5ec9d47e-7971-4a9c-ac01-55f18df56e73",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Title",
            "dataType": "string",
            "sourceColumn": "Title",
            "lineageTag": "d1e4b75a-bce9-4810-929f-736ce2a704b5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Name",
            "dataType": "string",
            "sourceColumn": "Name",
            "lineageTag": "dea2f5b9-a1e9-470d-a078-3c8814658a14",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Birth Date",
            "dataType": "dateTime",
            "sourceColumn": "Birth Date",
            "formatString": "Short Date",
            "lineageTag": "e937f3c2-bf50-4430-b580-967e6c5fbcd7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Marital Status",
            "dataType": "string",
            "sourceColumn": "Marital Status",
            "lineageTag": "ab13fc38-e64d-450a-a027-fa4227712189",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Gender",
            "dataType": "string",
            "sourceColumn": "Gender",
            "lineageTag": "b3fb7608-04e1-44dc-8d2f-1e882a3b08fd",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Yearly Income",
            "dataType": "decimal",
            "sourceColumn": "Yearly Income",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "e6b85ca4-5c0c-447c-8d9f-eeec7700aa06",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Total Children",
            "dataType": "int64",
            "sourceColumn": "Total Children",
            "lineageTag": "4d1cd21f-0a22-42a5-94a0-155163ed2b3f",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Children At Home",
            "dataType": "int64",
            "sourceColumn": "Children At Home",
            "lineageTag": "d8648732-2cae-4912-9398-9913ea9f4c83",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Education",
            "dataType": "string",
            "sourceColumn": "Education",
            "lineageTag": "d2739642-080f-44e1-99e0-aff8b4400cb7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Occupation",
            "dataType": "string",
            "sourceColumn": "Occupation",
            "lineageTag": "6d396ce7-cd22-4904-9521-83562f5f2a86",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "House Ownership",
            "dataType": "string",
            "sourceColumn": "House Ownership",
            "lineageTag": "76781aed-aff3-428f-a68f-791556f844c1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Cars Owned",
            "dataType": "int64",
            "sourceColumn": "Cars Owned",
            "lineageTag": "c235b7c1-2333-497f-aa41-bbc6f4e740e2",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Continent",
            "dataType": "string",
            "sourceColumn": "Continent",
            "lineageTag": "503c5c60-cef6-4b0f-992d-8b6b948cda06",
            "dataCategory": "Continent",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City",
            "lineageTag": "15f6f488-5fe3-48ed-94c4-5f3242b3a91c",
            "dataCategory": "City",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "State",
            "dataType": "string",
            "sourceColumn": "State",
            "lineageTag": "cd1cbeeb-e5b9-437d-8e29-3f20526ec731",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Country",
            "dataType": "string",
            "sourceColumn": "Country",
            "lineageTag": "577119aa-cad9-4cb1-9165-9e61496d18b7",
            "dataCategory": "Country",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Date First Purchase",
            "dataType": "dateTime",
            "sourceColumn": "Date First Purchase",
            "formatString": "Short Date",
            "lineageTag": "1b3b9654-2bce-4bed-bf87-82da0e442b6f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Customer Type",
            "dataType": "string",
            "sourceColumn": "Customer Type",
            "lineageTag": "b2cf25d2-baf2-400c-880b-863e2b4ee92d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Company Name",
            "dataType": "string",
            "sourceColumn": "Company Name",
            "lineageTag": "88c3d7d9-e86c-4bb5-9c9f-097ab7846bf5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Customer",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"Demo\", \"ContosoRetailDW\", [Query=\"SELECT [DaxBook].[Customer].* #(tab)#(tab)FROM [DaxBook].[Customer]\"]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"CustomerKey\", \"CustomerKey\"}, {\"GeographyKey\", \"GeographyKey\"}, {\"Customer Code\", \"Customer Code\"}, {\"Title\", \"Title\"}, {\"Name\", \"Name\"}, {\"Birth Date\", \"Birth Date\"}, {\"Marital Status\", \"Marital Status\"}, {\"Gender\", \"Gender\"}, {\"Yearly Income\", \"Yearly Income\"}, {\"Total Children\", \"Total Children\"}, {\"Children At Home\", \"Children At Home\"}, {\"Education\", \"Education\"}, {\"Occupation\", \"Occupation\"}, {\"House Ownership\", \"House Ownership\"}, {\"Cars Owned\", \"Cars Owned\"}, {\"Continent\", \"Continent\"}, {\"City\", \"City\"}, {\"State\", \"State\"}, {\"Country\", \"Country\"}, {\"Date First Purchase\", \"Date First Purchase\"}, {\"Customer Type\", \"Customer Type\"}, {\"Company Name\", \"Company Name\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"CustomerKey\", Int64.Type}, {\"GeographyKey\", Int64.Type}, {\"Customer Code\", type text}, {\"Title\", type text}, {\"Name\", type text}, {\"Birth Date\", type datetime}, {\"Marital Status\", type text}, {\"Gender\", type text}, {\"Yearly Income\", type number}, {\"Total Children\", Int64.Type}, {\"Children At Home\", Int64.Type}, {\"Education\", type text}, {\"Occupation\", type text}, {\"House Ownership\", type text}, {\"Cars Owned\", Int64.Type}, {\"Continent\", type text}, {\"City\", type text}, {\"State\", type text}, {\"Country\", type text}, {\"Date First Purchase\", type datetime}, {\"Customer Type\", type text}, {\"Company Name\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ]
      },
      {
        "name": "Date",
        "lineageTag": "10fbe02c-de98-4737-8b66-96c30962faa0",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "formatString": "Short Date",
            "lineageTag": "e4dafeb4-f3ee-4fa5-9c95-9507ad9033a2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DateKey",
            "lineageTag": "ff2325c7-e069-4594-9dc1-11a89ec78a36",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Calendar Year Number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Calendar Year Number",
            "lineageTag": "2b179101-f11c-45c7-b02a-9d4905eca64b",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Calendar Year",
            "dataType": "string",
            "sourceColumn": "Calendar Year",
            "sortByColumn": "Calendar Year Number",
            "lineageTag": "d8e2f205-2f23-471a-9a45-4cb06f9b61fd",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Calendar Year Quarter Number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Calendar Year Quarter Number",
            "lineageTag": "2a78f9f9-f971-4b7d-87c4-f8cfec00f1c7",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Calendar Year Quarter",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Calendar Year Quarter",
            "sortByColumn": "Calendar Year Quarter Number",
            "lineageTag": "83860b29-6f14-4d33-8e26-acc55732c2af",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Calendar Year Month Number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Calendar Year Month Number",
            "lineageTag": "8f8485f5-cd34-4ca2-85d1-1a0ee4ec35db",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Calendar Year Month",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Calendar Year Month",
            "sortByColumn": "Calendar Year Month Number",
            "lineageTag": "f91b3118-20da-4723-92ff-32bd8eb9336d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Month Number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Month Number",
            "lineageTag": "06abf063-d781-4e45-9f7d-f4a939cdb6f8",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Month",
            "dataType": "string",
            "sourceColumn": "Month",
            "sortByColumn": "Month Number",
            "lineageTag": "98a96adb-8c00-4d40-92cd-8aaf57bae198",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Day of Week Number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Day of Week Number",
            "lineageTag": "3aef47f5-08c0-4f82-9b00-a220dca2f5cf",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Day of Week",
            "dataType": "string",
            "sourceColumn": "Day of Week",
            "sortByColumn": "Day of Week Number",
            "lineageTag": "23e291dd-7278-4ee0-905f-7c64ec7fac1d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Fiscal Year Number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Fiscal Year Number",
            "lineageTag": "d164a46e-20e8-450b-b47e-7cc75eff15a3",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Fiscal Year",
            "dataType": "string",
            "sourceColumn": "Fiscal Year",
            "sortByColumn": "Fiscal Year Number",
            "lineageTag": "acef886f-158a-4492-8e5c-eb9146fe8510",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Fiscal Quarter Number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Fiscal Quarter Number",
            "lineageTag": "cd451b33-f35c-47de-bd68-d142beb75d9b",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Fiscal Quarter",
            "dataType": "string",
            "sourceColumn": "Fiscal Quarter",
            "sortByColumn": "Fiscal Quarter Number",
            "lineageTag": "6a25b27e-3a9c-4d57-a36e-5d5e53387801",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Fiscal Year Quarter Number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Fiscal Year Quarter Number",
            "lineageTag": "95bed685-6a3e-4ba0-b196-cccc8ede4f34",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Fiscal Year Quarter",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Fiscal Year Quarter",
            "sortByColumn": "Fiscal Year Quarter Number",
            "lineageTag": "42efae7d-7b50-4e82-96ce-668c23adb8fa",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Fiscal Month Number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Fiscal Month Number",
            "lineageTag": "dd9c7e87-7012-4e2d-90a8-a3ae8489f2c3",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Fiscal Month",
            "dataType": "string",
            "sourceColumn": "Fiscal Month",
            "sortByColumn": "Fiscal Month Number",
            "lineageTag": "2fdd9ac1-4014-453a-a940-c86b0c3aa54a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Working Day",
            "dataType": "string",
            "sourceColumn": "Working Day",
            "lineageTag": "faddf418-e7e8-4539-b407-b69e010397c3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Is Holiday",
            "dataType": "int64",
            "sourceColumn": "Is Holiday",
            "lineageTag": "203bf97d-5611-436c-9e58-06dccf250e47",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Holiday Name",
            "dataType": "string",
            "sourceColumn": "Holiday Name",
            "lineageTag": "bb083b35-c592-4823-ae9d-00f470d20e8e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Europe Season",
            "dataType": "string",
            "sourceColumn": "Europe Season",
            "lineageTag": "9decb163-c0ea-4c83-958d-f01d161774a3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "North America Season",
            "dataType": "string",
            "sourceColumn": "North America Season",
            "lineageTag": "e5bc4819-9e5f-4a41-b187-76ee19246e7d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Asia Season",
            "dataType": "string",
            "sourceColumn": "Asia Season",
            "lineageTag": "b182c242-fcb6-4fbe-ab64-72824e4dd2f2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Date",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"Demo\", \"ContosoRetailDW\", [Query=\"SELECT [DaxBook].[Date].* #(tab)#(tab)FROM [DaxBook].[Date]\"]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"Date\", \"Date\"}, {\"DateKey\", \"DateKey\"}, {\"Calendar Year Number\", \"Calendar Year Number\"}, {\"Calendar Year\", \"Calendar Year\"}, {\"Calendar Year Quarter Number\", \"Calendar Year Quarter Number\"}, {\"Calendar Year Quarter\", \"Calendar Year Quarter\"}, {\"Calendar Year Month Number\", \"Calendar Year Month Number\"}, {\"Calendar Year Month\", \"Calendar Year Month\"}, {\"Month Number\", \"Month Number\"}, {\"Month\", \"Month\"}, {\"Day of Week Number\", \"Day of Week Number\"}, {\"Day of Week\", \"Day of Week\"}, {\"Fiscal Year Number\", \"Fiscal Year Number\"}, {\"Fiscal Year\", \"Fiscal Year\"}, {\"Fiscal Quarter Number\", \"Fiscal Quarter Number\"}, {\"Fiscal Quarter\", \"Fiscal Quarter\"}, {\"Fiscal Year Quarter Number\", \"Fiscal Year Quarter Number\"}, {\"Fiscal Year Quarter\", \"Fiscal Year Quarter\"}, {\"Fiscal Month Number\", \"Fiscal Month Number\"}, {\"Fiscal Month\", \"Fiscal Month\"}, {\"Working Day\", \"Working Day\"}, {\"Is Holiday\", \"Is Holiday\"}, {\"Holiday Name\", \"Holiday Name\"}, {\"Europe Season\", \"Europe Season\"}, {\"North America Season\", \"North America Season\"}, {\"Asia Season\", \"Asia Season\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"Date\", type datetime}, {\"DateKey\", Int64.Type}, {\"Calendar Year Number\", Int64.Type}, {\"Calendar Year\", type text}, {\"Calendar Year Quarter Number\", Int64.Type}, {\"Calendar Year Quarter\", type text}, {\"Calendar Year Month Number\", Int64.Type}, {\"Calendar Year Month\", type text}, {\"Month Number\", Int64.Type}, {\"Month\", type text}, {\"Day of Week Number\", Int64.Type}, {\"Day of Week\", type text}, {\"Fiscal Year Number\", Int64.Type}, {\"Fiscal Year\", type text}, {\"Fiscal Quarter Number\", Int64.Type}, {\"Fiscal Quarter\", type text}, {\"Fiscal Year Quarter Number\", Int64.Type}, {\"Fiscal Year Quarter\", type text}, {\"Fiscal Month Number\", Int64.Type}, {\"Fiscal Month\", type text}, {\"Working Day\", type text}, {\"Is Holiday\", Int64.Type}, {\"Holiday Name\", type text}, {\"Europe Season\", type text}, {\"North America Season\", type text}, {\"Asia Season\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Fiscal Quarter-Month",
            "lineageTag": "9e03e924-2eb4-46d8-a6ea-92223e70ffcb",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Fiscal Year",
                "lineageTag": "aa6dbd87-76cd-4978-a9fd-943a2aa518fe"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Fiscal Year Quarter",
                "lineageTag": "c5f83882-bfd7-4a6e-8151-1df149df921c"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Calendar Year Month",
                "lineageTag": "646aef0e-1235-4b51-ad88-4da4401c2625"
              },
              {
                "name": "Date",
                "ordinal": 3,
                "column": "Date",
                "lineageTag": "f1136561-78f2-4873-9639-c61e05b68510"
              }
            ]
          },
          {
            "name": "Calendar Quarter-Month",
            "lineageTag": "d8a6358e-d96c-44ba-b129-d5ffd79b0cc0",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Calendar Year",
                "lineageTag": "e3065b8d-302b-482b-9ee0-3c2b6d61b9b6"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Calendar Year Quarter",
                "lineageTag": "82fc680a-b4b0-4347-9f16-1ef8d370b4d9"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Calendar Year Month",
                "lineageTag": "3f4f7a70-8112-445f-afe8-e5fa354290d7"
              },
              {
                "name": "Date",
                "ordinal": 3,
                "column": "Date",
                "lineageTag": "5f2d2ce1-7f22-47e2-8668-efba08acd586"
              }
            ]
          },
          {
            "name": "Calendar",
            "lineageTag": "274840ba-18d1-46f3-a26b-889a5ae18ebe",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Calendar Year",
                "lineageTag": "6e7b4603-3796-49f9-a925-b4b18b94951c"
              },
              {
                "name": "Month",
                "ordinal": 1,
                "column": "Calendar Year Month",
                "lineageTag": "54b253ad-3b83-468c-8810-7492730db7fc"
              },
              {
                "name": "Date",
                "ordinal": 2,
                "column": "Date",
                "lineageTag": "64dc2837-2f4a-4e1c-9c43-5a173937fd9a"
              }
            ]
          },
          {
            "name": "Fiscal",
            "lineageTag": "775f1f9c-6976-49fc-be26-53c13b469be3",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Fiscal Year",
                "lineageTag": "bc542c2b-a503-456d-8a4c-1736d15005d2"
              },
              {
                "name": "Month",
                "ordinal": 1,
                "column": "Calendar Year Month",
                "lineageTag": "b42249ba-2d9a-4b31-98c7-fa5152783821"
              },
              {
                "name": "Date",
                "ordinal": 2,
                "column": "Date",
                "lineageTag": "107ab6d8-dbf9-488c-89f9-fa61647d40c9"
              }
            ]
          }
        ]
      },
      {
        "name": "Product",
        "lineageTag": "44d56098-f6ba-43c1-991f-dfc7b1987357",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ProductKey",
            "lineageTag": "76c095d9-9e2e-47aa-930d-5bff6649e1e7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Product Code",
            "dataType": "string",
            "sourceColumn": "Product Code",
            "lineageTag": "6d8fbc78-83ee-4d67-b3c1-29cf1306c3a5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Product Name",
            "dataType": "string",
            "sourceColumn": "Product Name",
            "lineageTag": "2bcd2bb7-6b8d-422a-959b-366679baa94c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Product Description",
            "dataType": "string",
            "sourceColumn": "Product Description",
            "lineageTag": "62d96467-ec24-406d-b807-c542e0fc4ba9",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ProductSubcategoryKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ProductSubcategoryKey",
            "lineageTag": "d587ee67-5a3e-47bf-8094-c2a9221cc21d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Manufacturer",
            "dataType": "string",
            "sourceColumn": "Manufacturer",
            "lineageTag": "217bba3b-f8bd-49a7-95a6-74363a1e7b4e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Brand",
            "dataType": "string",
            "sourceColumn": "Brand",
            "lineageTag": "8e8d0933-6dc6-43b7-9134-ee6c321ec814",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Class",
            "dataType": "string",
            "sourceColumn": "Class",
            "lineageTag": "97ded8d1-c0f8-4ea0-90d9-6203ab64f8ae",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Style",
            "dataType": "string",
            "sourceColumn": "Style",
            "lineageTag": "191248b3-cadd-4c9d-9dcb-230dd821d988",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Color",
            "dataType": "string",
            "sourceColumn": "Color",
            "lineageTag": "20b94c5b-9e71-44d8-8611-c0f058bf370d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Size",
            "dataType": "string",
            "sourceColumn": "Size",
            "lineageTag": "9328cd66-facd-475c-9bcf-abcb4c3eaa24",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Weight",
            "dataType": "double",
            "sourceColumn": "Weight",
            "lineageTag": "550f518c-e99b-4a0c-82ad-69f614376194",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Weight Unit Measure",
            "dataType": "string",
            "sourceColumn": "Weight Unit Measure",
            "lineageTag": "6d1a31cf-8177-4943-b0d5-52a43a61af43",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Stock Type Code",
            "dataType": "string",
            "sourceColumn": "Stock Type Code",
            "lineageTag": "440576cd-b93d-4f23-abd5-a7021d15f9a7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Stock Type",
            "dataType": "string",
            "sourceColumn": "Stock Type",
            "lineageTag": "e09f7594-3851-4d28-ba87-ef5e2174a7a0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Unit Cost",
            "dataType": "decimal",
            "sourceColumn": "Unit Cost",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "73faedc9-df4f-45c4-a75b-345cf463afe3",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Unit Price",
            "dataType": "decimal",
            "sourceColumn": "Unit Price",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "471a0f31-1f79-4fd0-9b45-db624efe8422",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Available Date",
            "dataType": "dateTime",
            "sourceColumn": "Available Date",
            "formatString": "Short Date",
            "lineageTag": "0a54a2bc-7695-44c9-b799-128729aa329a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Status",
            "dataType": "string",
            "sourceColumn": "Status",
            "lineageTag": "d7ce1baa-6985-4a5f-99b2-dd6674de313d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Product",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"Demo\", \"ContosoRetailDW\", [Query=\"SELECT [DaxBook].[Product].* #(tab)#(tab)FROM [DaxBook].[Product]\"]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"ProductKey\", \"ProductKey\"}, {\"Product Code\", \"Product Code\"}, {\"Product Name\", \"Product Name\"}, {\"Product Description\", \"Product Description\"}, {\"ProductSubcategoryKey\", \"ProductSubcategoryKey\"}, {\"Manufacturer\", \"Manufacturer\"}, {\"Brand\", \"Brand\"}, {\"Class\", \"Class\"}, {\"Style\", \"Style\"}, {\"Color\", \"Color\"}, {\"Size\", \"Size\"}, {\"Weight\", \"Weight\"}, {\"Weight Unit Measure\", \"Weight Unit Measure\"}, {\"Stock Type Code\", \"Stock Type Code\"}, {\"Stock Type\", \"Stock Type\"}, {\"Unit Cost\", \"Unit Cost\"}, {\"Unit Price\", \"Unit Price\"}, {\"Available Date\", \"Available Date\"}, {\"Status\", \"Status\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"ProductKey\", Int64.Type}, {\"Product Code\", type text}, {\"Product Name\", type text}, {\"Product Description\", type text}, {\"ProductSubcategoryKey\", Int64.Type}, {\"Manufacturer\", type text}, {\"Brand\", type text}, {\"Class\", type text}, {\"Style\", type text}, {\"Color\", type text}, {\"Size\", type text}, {\"Weight\", type number}, {\"Weight Unit Measure\", type text}, {\"Stock Type Code\", type text}, {\"Stock Type\", type text}, {\"Unit Cost\", type number}, {\"Unit Price\", type number}, {\"Available Date\", type datetime}, {\"Status\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ]
      },
      {
        "name": "Product Category",
        "lineageTag": "dd1ac8b3-67ca-48e0-8d7b-36333933b2fb",
        "columns": [
          {
            "name": "ProductCategoryKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ProductCategoryKey",
            "lineageTag": "0242573f-72e9-4c33-8e30-6f51823fa967",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Category Code",
            "dataType": "string",
            "sourceColumn": "Category Code",
            "lineageTag": "7d352744-ca70-4486-ad4f-b8f510e94758",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Category",
            "dataType": "string",
            "sourceColumn": "Category",
            "lineageTag": "0872abfe-0e75-454e-8dca-81ba913773de",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Product Category",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"Demo\", \"ContosoRetailDW\", [Query=\"SELECT [DaxBook].[Product Category].* #(tab)#(tab)FROM [DaxBook].[Product Category]\"]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"ProductCategoryKey\", \"ProductCategoryKey\"}, {\"Category Code\", \"Category Code\"}, {\"Category\", \"Category\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"ProductCategoryKey\", Int64.Type}, {\"Category Code\", type text}, {\"Category\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ]
      },
      {
        "name": "Product Subcategory",
        "lineageTag": "268ba95f-ffc0-4a0a-ae5f-61885bb3580e",
        "columns": [
          {
            "name": "ProductSubcategoryKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ProductSubcategoryKey",
            "lineageTag": "e5f8b3a0-b6da-4ff6-a67e-255f4402f133",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Subcategory Code",
            "dataType": "string",
            "sourceColumn": "Subcategory Code",
            "lineageTag": "3c908f4c-c040-4eb2-9328-7ba5f96542a9",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Subcategory",
            "dataType": "string",
            "sourceColumn": "Subcategory",
            "lineageTag": "97172fed-4f5b-45c3-8961-2b2ee729f69d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ProductCategoryKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ProductCategoryKey",
            "lineageTag": "59ef8bd1-b3e8-4b26-9fd9-a05dd981a9e9",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Product Subcategory",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"Demo\", \"ContosoRetailDW\", [Query=\"SELECT [DaxBook].[Product Subcategory].* #(tab)#(tab)FROM [DaxBook].[Product Subcategory]\"]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"ProductSubcategoryKey\", \"ProductSubcategoryKey\"}, {\"Subcategory Code\", \"Subcategory Code\"}, {\"Subcategory\", \"Subcategory\"}, {\"ProductCategoryKey\", \"ProductCategoryKey\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"ProductSubcategoryKey\", Int64.Type}, {\"Subcategory Code\", type text}, {\"Subcategory\", type text}, {\"ProductCategoryKey\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ]
      },
      {
        "name": "Promotion",
        "lineageTag": "0e812719-a75f-4e75-ae11-0021180338c7",
        "columns": [
          {
            "name": "PromotionKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PromotionKey",
            "lineageTag": "b61b3599-69e5-4007-b292-0a8edc58493c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Promotion Code",
            "dataType": "string",
            "sourceColumn": "Promotion Code",
            "lineageTag": "c00e4ce1-d5d1-444b-9156-28fe3ec3e79d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Promotion",
            "dataType": "string",
            "sourceColumn": "Promotion",
            "lineageTag": "b7795949-70bc-4b63-b321-8528fecce696",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Discount",
            "dataType": "double",
            "sourceColumn": "Discount",
            "lineageTag": "e26b4abf-4baa-4cc9-8468-fd7fbe52b8d5",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Promotion Type",
            "dataType": "string",
            "sourceColumn": "Promotion Type",
            "lineageTag": "4dd27947-76a5-4abd-8ce9-54d4ca3ac350",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Promotion Category",
            "dataType": "string",
            "sourceColumn": "Promotion Category",
            "lineageTag": "297aa337-73a5-4801-8ea0-7a9b7d6a28d8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Start Date",
            "dataType": "dateTime",
            "sourceColumn": "Start Date",
            "formatString": "Short Date",
            "lineageTag": "38b2eff7-8561-4342-aae7-835957cc2f20",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "End Date",
            "dataType": "dateTime",
            "sourceColumn": "End Date",
            "formatString": "Short Date",
            "lineageTag": "35db4cd8-a9cd-483f-87bf-d7e6bd89ee9f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Promotion",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"Demo\", \"ContosoRetailDW\", [Query=\"SELECT [DaxBook].[Promotion].* #(tab)#(tab)FROM [DaxBook].[Promotion]\"]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"PromotionKey\", \"PromotionKey\"}, {\"Promotion Code\", \"Promotion Code\"}, {\"Promotion\", \"Promotion\"}, {\"Discount\", \"Discount\"}, {\"Promotion Type\", \"Promotion Type\"}, {\"Promotion Category\", \"Promotion Category\"}, {\"Start Date\", \"Start Date\"}, {\"End Date\", \"End Date\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"PromotionKey\", Int64.Type}, {\"Promotion Code\", type text}, {\"Promotion\", type text}, {\"Discount\", type number}, {\"Promotion Type\", type text}, {\"Promotion Category\", type text}, {\"Start Date\", type datetime}, {\"End Date\", type datetime}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ]
      },
      {
        "name": "Sales",
        "lineageTag": "1ccc0c4d-ecb1-4720-ae58-08d7d436c839",
        "columns": [
          {
            "name": "StoreKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "StoreKey",
            "lineageTag": "5a048f1b-2d78-49bf-b529-15eab30be0b2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ProductKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ProductKey",
            "lineageTag": "e7eb640a-b274-4864-bbb6-aac398df26d3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "PromotionKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PromotionKey",
            "lineageTag": "a4838f19-b6f4-4d55-b427-0567a5dafd83",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "CurrencyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CurrencyKey",
            "lineageTag": "a7a4e9be-88c0-413d-85d5-489503eac869",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CustomerKey",
            "lineageTag": "d4a385ab-4264-44ee-bb77-1a3976a8887a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "OrderDateKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "OrderDateKey",
            "lineageTag": "b805f211-3b95-4a80-9303-652855fb495f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "DueDateKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DueDateKey",
            "lineageTag": "e81e39f8-0273-4f75-a0d1-3d6503eae779",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "DeliveryDateKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DeliveryDateKey",
            "lineageTag": "52ece625-928b-410b-93bd-38143b7ed1a4",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Order Date",
            "dataType": "dateTime",
            "sourceColumn": "Order Date",
            "formatString": "Short Date",
            "lineageTag": "c6d2b93c-433a-4fa2-b937-27e1bc6aece1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Due Date",
            "dataType": "dateTime",
            "sourceColumn": "Due Date",
            "formatString": "Short Date",
            "lineageTag": "e540892c-43fc-4878-8868-779d4d1699f5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Delivery Date",
            "dataType": "dateTime",
            "sourceColumn": "Delivery Date",
            "formatString": "Short Date",
            "lineageTag": "f91bb73b-0717-4f64-95d8-e3b1cdfce5e8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Quantity",
            "dataType": "int64",
            "sourceColumn": "Quantity",
            "lineageTag": "03fc5231-08fd-4400-b141-a283cb77cdff",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Unit Price",
            "dataType": "decimal",
            "sourceColumn": "Unit Price",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "01184a8f-264e-4f53-ad8b-63fe416be5e7",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Unit Discount",
            "dataType": "decimal",
            "sourceColumn": "Unit Discount",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "176c2362-87b1-43d5-adc4-84ef6da7da6b",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Unit Cost",
            "dataType": "decimal",
            "sourceColumn": "Unit Cost",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "c61c636f-3e77-4cc6-91b4-0ac7f3a78a61",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Net Price",
            "dataType": "decimal",
            "sourceColumn": "Net Price",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "264b309f-b720-46f0-8377-d5bb4a06a525",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Sales",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"Demo\", \"ContosoRetailDW\", [Query=\"SELECT [DaxBook].[Sales].* #(tab)#(tab)FROM [DaxBook].[Sales]\"]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"StoreKey\", \"StoreKey\"}, {\"ProductKey\", \"ProductKey\"}, {\"PromotionKey\", \"PromotionKey\"}, {\"CurrencyKey\", \"CurrencyKey\"}, {\"CustomerKey\", \"CustomerKey\"}, {\"OrderDateKey\", \"OrderDateKey\"}, {\"DueDateKey\", \"DueDateKey\"}, {\"DeliveryDateKey\", \"DeliveryDateKey\"}, {\"Order Date\", \"Order Date\"}, {\"Due Date\", \"Due Date\"}, {\"Delivery Date\", \"Delivery Date\"}, {\"Quantity\", \"Quantity\"}, {\"Unit Price\", \"Unit Price\"}, {\"Unit Discount\", \"Unit Discount\"}, {\"Unit Cost\", \"Unit Cost\"}, {\"Net Price\", \"Net Price\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"StoreKey\", Int64.Type}, {\"ProductKey\", Int64.Type}, {\"PromotionKey\", Int64.Type}, {\"CurrencyKey\", Int64.Type}, {\"CustomerKey\", Int64.Type}, {\"OrderDateKey\", Int64.Type}, {\"DueDateKey\", Int64.Type}, {\"DeliveryDateKey\", Int64.Type}, {\"Order Date\", type datetime}, {\"Due Date\", type datetime}, {\"Delivery Date\", type datetime}, {\"Quantity\", Int64.Type}, {\"Unit Price\", type number}, {\"Unit Discount\", type number}, {\"Unit Cost\", type number}, {\"Net Price\", type number}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Sales Amount",
            "expression": "SUMX ( Sales, Sales[Quantity] * Sales[Unit Price] )",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "bf2e76b2-a867-4be2-b893-e20431cc44f8",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Sales Rows",
            "expression": "COUNTROWS ( Sales )",
            "formatString": "#,0",
            "lineageTag": "68473302-2da9-4ed4-be4f-3f7372b6f00b"
          },
          {
            "name": "Sales Cost",
            "expression": "SUMX ( Sales, Sales[Quantity] * Sales[Unit Cost] )",
            "formatString": "\"\"\\ #,0.00;-\"\"\\ #,0.00;\"\"\\ #,0.00",
            "lineageTag": "3dc256be-3a5f-4eca-a97a-f411dbdcdaa3"
          },
          {
            "name": "Margin %",
            "expression": "DIVIDE ( [Sales Amount] -       [Sales Cost], [Sales Cost] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "5f4b083c-7cc0-49d4-9fa4-d3421fcbf9c2"
          }
        ]
      },
      {
        "name": "Store",
        "lineageTag": "6c318cd7-60af-4c38-a3e3-1f7973d90e89",
        "columns": [
          {
            "name": "StoreKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "StoreKey",
            "lineageTag": "5d837c7f-cb64-42df-bdbb-d765ba051063",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "GeographyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "GeographyKey",
            "lineageTag": "84bc7667-573a-4056-b324-a5ba93474ddc",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Store Manager",
            "dataType": "int64",
            "sourceColumn": "Store Manager",
            "lineageTag": "25f4cbbd-2dd7-4728-9f4b-ba64d060f5ef",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Store Type",
            "dataType": "string",
            "sourceColumn": "Store Type",
            "lineageTag": "21f55f76-8e0d-4ba5-80ca-9c50839a27fb",
            "dataCategory": "Company",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Store Name",
            "dataType": "string",
            "sourceColumn": "Store Name",
            "lineageTag": "d5804560-abcd-4f22-8c03-11a3d7f8c5d9",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Status",
            "dataType": "string",
            "sourceColumn": "Status",
            "lineageTag": "741bd823-a767-4c5c-b624-7a3626366154",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Open Date",
            "dataType": "dateTime",
            "sourceColumn": "Open Date",
            "formatString": "Short Date",
            "lineageTag": "663a717b-e9f4-441b-a3a8-c6efbc8c2432",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Close Date",
            "dataType": "dateTime",
            "sourceColumn": "Close Date",
            "formatString": "Short Date",
            "lineageTag": "9d76f5bd-1f6d-42a8-adde-f90e5a7d3907",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Zip Code",
            "dataType": "string",
            "sourceColumn": "Zip Code",
            "lineageTag": "106e31f2-198d-40ab-a501-45171a07d896",
            "dataCategory": "PostalCode",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Zip Code Extension",
            "dataType": "string",
            "sourceColumn": "Zip Code Extension",
            "lineageTag": "a84e9615-ac86-45a0-93a9-13326470fcfe",
            "dataCategory": "PostalCode",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Continent",
            "dataType": "string",
            "sourceColumn": "Continent",
            "lineageTag": "f2955fa3-759b-467b-8f5b-444263daa4a3",
            "dataCategory": "Continent",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City",
            "lineageTag": "3cdd1bde-9073-4335-9243-184e8ecc574c",
            "dataCategory": "City",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "State",
            "dataType": "string",
            "sourceColumn": "State",
            "lineageTag": "385074f4-1f46-4c7a-942c-e1ab27d71c54",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Country",
            "dataType": "string",
            "sourceColumn": "Country",
            "lineageTag": "111ba883-a540-4ec1-b56f-56135f8a8289",
            "dataCategory": "Country",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Close Reason",
            "dataType": "string",
            "sourceColumn": "Close Reason",
            "lineageTag": "e47c009d-2f0b-45bd-8f4b-8725db4ec2fb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Employees",
            "dataType": "int64",
            "sourceColumn": "Employees",
            "lineageTag": "f05d4c64-a327-4412-97d9-3ffa500d45ef",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Selling Area",
            "dataType": "double",
            "sourceColumn": "Selling Area",
            "lineageTag": "2cd03ac2-a20d-495d-92c1-2f6952a936b4",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Last Remodel Date",
            "dataType": "dateTime",
            "sourceColumn": "Last Remodel Date",
            "formatString": "Short Date",
            "lineageTag": "e5794a1d-2bda-417b-aa31-3ab27484da6d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Store",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"Demo\", \"ContosoRetailDW\", [Query=\"SELECT [DaxBook].[Store].* #(tab)#(tab)FROM [DaxBook].[Store]\"]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"StoreKey\", \"StoreKey\"}, {\"GeographyKey\", \"GeographyKey\"}, {\"Store Manager\", \"Store Manager\"}, {\"Store Type\", \"Store Type\"}, {\"Store Name\", \"Store Name\"}, {\"Status\", \"Status\"}, {\"Open Date\", \"Open Date\"}, {\"Close Date\", \"Close Date\"}, {\"Zip Code\", \"Zip Code\"}, {\"Zip Code Extension\", \"Zip Code Extension\"}, {\"Continent\", \"Continent\"}, {\"City\", \"City\"}, {\"State\", \"State\"}, {\"Country\", \"Country\"}, {\"Close Reason\", \"Close Reason\"}, {\"Employees\", \"Employees\"}, {\"Selling Area\", \"Selling Area\"}, {\"Last Remodel Date\", \"Last Remodel Date\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"StoreKey\", Int64.Type}, {\"GeographyKey\", Int64.Type}, {\"Store Manager\", Int64.Type}, {\"Store Type\", type text}, {\"Store Name\", type text}, {\"Status\", type text}, {\"Open Date\", type datetime}, {\"Close Date\", type datetime}, {\"Zip Code\", type text}, {\"Zip Code Extension\", type text}, {\"Continent\", type text}, {\"City\", type text}, {\"State\", type text}, {\"Country\", type text}, {\"Close Reason\", type text}, {\"Employees\", Int64.Type}, {\"Selling Area\", type number}, {\"Last Remodel Date\", type datetime}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ]
      },
      {
        "name": "__measures",
        "lineageTag": "641b0f14-df9a-4f2d-94f2-d3bc35308158",
        "partitions": [
          {
            "name": "__measures-d001dc4e-3ab6-407a-96c6-463ce5c7813d",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "M1",
            "expression": "1",
            "formatString": "0",
            "lineageTag": "425f5e15-f238-41d0-be18-c2a61a4617f5"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "510526ce-d8d3-4702-9935-d8e890f49dd5",
        "fromTable": "Product",
        "fromColumn": "ProductSubcategoryKey",
        "toTable": "Product Subcategory",
        "toColumn": "ProductSubcategoryKey"
      },
      {
        "name": "65348b61-fc6d-44d5-b38e-f85bf1572c7b",
        "fromTable": "Product Subcategory",
        "fromColumn": "ProductCategoryKey",
        "toTable": "Product Category",
        "toColumn": "ProductCategoryKey"
      },
      {
        "name": "e32ed2c1-e502-4141-a690-a213dbfaabc4",
        "fromTable": "Sales",
        "fromColumn": "StoreKey",
        "toTable": "Store",
        "toColumn": "StoreKey"
      },
      {
        "name": "058f7212-608d-45d6-9ae6-917b2f0d7038",
        "fromTable": "Sales",
        "fromColumn": "PromotionKey",
        "toTable": "Promotion",
        "toColumn": "PromotionKey"
      },
      {
        "name": "0301e042-5e56-4141-a2a8-0732f7506eb1",
        "fromTable": "Sales",
        "fromColumn": "ProductKey",
        "toTable": "Product",
        "toColumn": "ProductKey"
      },
      {
        "name": "b0c3f942-4a85-4b60-992a-d56bd8e9b586",
        "fromTable": "Sales",
        "fromColumn": "CurrencyKey",
        "toTable": "Currency",
        "toColumn": "CurrencyKey"
      },
      {
        "name": "e64eb6bd-6791-4340-a1f4-a88dd95cd269",
        "fromTable": "Sales",
        "fromColumn": "OrderDateKey",
        "toTable": "Date",
        "toColumn": "DateKey"
      },
      {
        "name": "776151bf-b94c-4742-b9af-ed80a91cac84",
        "fromTable": "Sales",
        "fromColumn": "DueDateKey",
        "toTable": "Date",
        "toColumn": "DateKey",
        "isActive": false
      },
      {
        "name": "45ae26c6-e97e-4457-8856-dec074dbc041",
        "fromTable": "Sales",
        "fromColumn": "DeliveryDateKey",
        "toTable": "Date",
        "toColumn": "DateKey",
        "isActive": false
      },
      {
        "name": "87e2f343-3a02-4f10-8458-81370b8e0c16",
        "fromTable": "Sales",
        "fromColumn": "CustomerKey",
        "toTable": "Customer",
        "toColumn": "CustomerKey"
      }
    ],
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Version": "1.0.0",
            "Language": "en-US",
            "DynamicImprovement": "HighConfidence"
          },
          "contentType": "json"
        }
      }
    ],
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.104.941.0 (22.04)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Currency\",\"Customer\",\"Date\",\"Product\",\"Product Category\",\"Product Subcategory\",\"Promotion\",\"Sales\",\"Store\",\"__measures\"]"
      },
      {
        "name": "TabularEditor_SerializeOptions",
        "value": "{\"IgnoreInferredObjects\":true,\"IgnoreInferredProperties\":true,\"IgnoreTimestamps\":true,\"SplitMultilineStrings\":true,\"PrefixFilenames\":false,\"LocalTranslations\":false,\"LocalPerspectives\":false,\"LocalRelationships\":false,\"Levels\":[\"Data Sources\",\"Shared Expressions\",\"Perspectives\",\"Relationships\",\"Roles\",\"Tables\",\"Tables/Columns\",\"Tables/Hierarchies\",\"Tables/Measures\",\"Tables/Partitions\",\"Tables/Calculation Items\",\"Translations\"]}"
      }
    ]
  }
}